import type { Metadata } from "next";
import Link from "next/link";
import { SourceList } from "@/components/source-list";
import { GuideLibrary } from "@/components/guide-library";
import { TrackedLink } from "@/components/tracked-link";
import { PriceHighlights } from "@/components/price-list";
import { guidesIntro, guidesTitle, guidesDescription } from "@/lib/guides-hub";
import { guideCards, guideCategories, newGuides, GUIDES_DATE, guideAssessmentHref } from "@/lib/guides";
import { pages, SITE_URL, UPDATED_ISO_DATE } from "@/lib/site";
import { reviewFor, approvedReviewer } from "@/lib/medical-review";
import { OG_IMAGES, TWITTER_IMAGES } from "@/lib/seo";
export const metadata: Metadata = { title: { absolute: "Leczenie zębów w Turcji – Poradniki dla pacjentów z Polski" }, description: guidesDescription, alternates: { canonical: "/poradniki" }, robots: { index: true, follow: true }, openGraph: { images: OG_IMAGES, title: guidesTitle, description: guidesDescription, url: "/poradniki", type: "website" }, twitter: { images: TWITTER_IMAGES, card: "summary_large_image", title: guidesTitle, description: guidesDescription } };
export default function GuidesHub() {
  const url = `${SITE_URL}/poradniki`;
  const cards = guideCards.map((card, index) => { const page = card.href.startsWith("/poradniki/") ? newGuides[card.href.split("/").at(-1)!] : pages[card.href.slice(1)]; const review = reviewFor(page.slug, page.lastUpdated ?? UPDATED_ISO_DATE); const expert = approvedReviewer(review); return { ...card, number: index + 1, updated: page.lastUpdated ?? UPDATED_ISO_DATE, review: expert && review.reviewStatus === "reviewed" ? `Recenzja: ${expert.name}, ${review.reviewDate}` : "Recenzja medyczna: jeszcze nieprzeprowadzona" }; });
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", "@id": `${url}#webpage`, url, name: guidesTitle, description: guidesDescription, inLanguage: "pl-PL", datePublished: GUIDES_DATE, dateModified: GUIDES_DATE, author: { "@id": `${SITE_URL}/#organization` }, isPartOf: { "@id": `${SITE_URL}/#website` }, mainEntity: { "@type": "ItemList", numberOfItems: guideCards.length, itemListElement: guideCards.map((card, index) => ({ "@type": "ListItem", position: index + 1, name: card.title, description: card.description, url: `${SITE_URL}${card.href}` })) } };
  const breadcrumb = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Strona główna", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Poradniki", item: url }] };
  return <main><section className="page-hero"><div className="shell narrow"><nav aria-label="Ścieżka nawigacji"><Link href="/">Strona główna</Link> / Poradniki</nav><p className="eyebrow">Biblioteka poradników dla pacjentów</p><h1>{guidesTitle}</h1>{guidesIntro.map((text) => <p key={text}>{text}</p>)}<p className="hero-partner">Klinika partnerska: Akdeniz Dental, Antalya, Turcja</p><div className="button-row"><TrackedLink href={guideAssessmentHref("/poradniki", "guides_hub_top")} event="guide_contact_cta" tracking={{ guide_source: "/poradniki", cta_location: "guides_hub_top" }} className="button">Poproś o wstępną wycenę</TrackedLink><TrackedLink href="/koszt?guide_source=%2Fporadniki" event="guide_to_pricing" tracking={{ guide_source: "/poradniki", destination_path: "/koszt" }} className="text-link">Zobacz ceny leczenia</TrackedLink></div></div></section>
    <GuideLibrary cards={cards} categories={guideCategories} />
    <PriceHighlights guideSource="/poradniki"><p>Cena pojedynczej pozycji nie jest ceną całego planu ani wyjazdu. Hotel, loty, transfery i wsparcie po polsku ustal osobno w ofercie.</p></PriceHighlights>
    <section className="shell narrow content-section"><h2>Jak korzystać z poradników i sprawdzać informacje</h2><p>To stała biblioteka, a nie archiwum bloga. Metody, ceny i organizacja wyjazdu mają osobne przewodniki.</p><p>Recenzja jest przypisana do konkretnej strony i daty. Nowe poradniki nie mają jeszcze potwierdzonej recenzji medycznej. Opinie i materiały przed i po nie zastępują diagnozy ani nie gwarantują wyniku.</p><p><Link href="/nasi-lekarze">Poznaj lekarzy kliniki</Link> · <Link href="/eksperci">Profile recenzentów</Link> · <Link href="/weryfikacja-medyczna">Zakres recenzji</Link> · <Link href="/polityka-redakcyjna">Standard redakcyjny</Link> · <Link href="/pytania-i-odpowiedzi">Pytania pacjentów</Link></p><p>Autor: Redakcja serwisu. Publikacja i aktualizacja: <time dateTime={GUIDES_DATE}>30 września 2026</time>.</p></section>
    <SourceList className="shell narrow content-section sources" intro="Każdy przewodnik ma własną listę źródeł. Wspólne zasady i dane znajdziesz tutaj." sources={[{ label: "Cennik kliniki Akdeniz Dental (pozycje w EUR, z datą)", href: "/koszt#cennik" }, { label: "Polityka redakcyjna: autorstwo, źródła i korekty", href: "/polityka-redakcyjna" }, { label: "Weryfikacja medyczna: zasady i status recenzji", href: "/weryfikacja-medyczna" }, { label: "Pytania i odpowiedzi z odnośnikami do stron źródłowych", href: "/pytania-i-odpowiedzi" }]} />
    <section className="closing-cta"><div className="shell narrow"><p className="eyebrow">Wstępna wycena</p><h2>Zapytaj o zakres i koszt swojego leczenia</h2><p>Opisz po polsku swoje potrzeby. Ustalimy, jakie informacje są potrzebne do wstępnej oceny; ostateczny plan wymaga badania przez lekarza.</p><div className="button-row"><TrackedLink href={guideAssessmentHref("/poradniki", "guides_hub_bottom")} event="guide_contact_cta" tracking={{ guide_source: "/poradniki", cta_location: "guides_hub_bottom" }} className="button button-light">Poproś o wstępną wycenę</TrackedLink><TrackedLink href="/koszt?guide_source=%2Fporadniki" event="guide_to_pricing" tracking={{ guide_source: "/poradniki", destination_path: "/koszt" }} className="text-link">Zobacz ceny leczenia</TrackedLink></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /></main>;
}
