import type { Metadata } from "next";
import Link from "next/link";
import { verifiedExperts } from "@/lib/evidence";
import { OG_IMAGES, TWITTER_IMAGES } from "@/lib/seo";

export const metadata: Metadata = { title: "Eksperci", description: "Profile ekspertów i źródła potwierdzające ich tożsamość zawodową oraz status recenzji treści.", alternates: { canonical: "/eksperci" }, openGraph: { images: OG_IMAGES, title: "Eksperci – recenzenci medyczni", description: "Profile i zakres recenzji medycznych poszczególnych przewodników.", url: "/eksperci", type: "website" }, twitter: { images: TWITTER_IMAGES, card: "summary_large_image", title: "Eksperci – recenzenci medyczni", description: "Tożsamość, źródła i zakres recenzji medycznych." } };
export default function Experts() {
  return <main className="shell expert-profile content-section"><h1>Eksperci</h1><p>Profile przedstawiają potwierdzone informacje o tożsamości zawodowej. Samo umieszczenie eksperta na tej stronie nie oznacza, że zrecenzował treść serwisu.</p>{verifiedExperts.map((expert) => <section className="content-section" key={expert.slug}><p className="eyebrow">Recenzent medyczny serwisu</p><h2><Link href={expert.profileUrl}>Lek. dent. {expert.name}</Link></h2><p>{expert.introduction ?? "Dentysta, Antalya, Turcja. Założyciel i właściciel Akdeniz Dental, kliniki partnerskiej serwisu."}</p>{expert.reviewScope && <p>{expert.reviewScope}</p>}<p>Profil obejmuje biografię, obszary pracy i publiczne źródła zawodowe. Status recenzji każdej strony jest podany przy jej treści.</p><Link className="text-link" href={expert.profileUrl}>Zobacz profil i źródła →</Link></section>)}<section><h2>Zespół kliniki partnerskiej</h2><p>Poznaj lekarzy Akdeniz Dental, ich wykształcenie i obszary pracy. Obecność w zespole klinicznym nie oznacza recenzji treści serwisu.</p><Link className="text-link" href="/nasi-lekarze">Nasi lekarze →</Link></section></main>;
}
