import type { Metadata } from "next";
import Link from "next/link";
import { verifiedExperts } from "@/lib/evidence";
import { SourceList } from "@/components/source-list";
import { OG_IMAGES, TWITTER_IMAGES, breadcrumbList } from "@/lib/seo";

export const metadata: Metadata = { title: "Eksperci", description: "Profile recenzentów medycznych serwisu Zęby w Turcji: tożsamość zawodowa, powiązanie z kliniką, źródła i lista faktycznie zrecenzowanych stron.", alternates: { canonical: "/eksperci" }, openGraph: { images: OG_IMAGES, title: "Eksperci – recenzenci medyczni", description: "Profile i zakres recenzji medycznych poszczególnych przewodników.", url: "/eksperci", type: "website" }, twitter: { images: TWITTER_IMAGES, card: "summary_large_image", title: "Eksperci – recenzenci medyczni", description: "Tożsamość, źródła i zakres recenzji medycznych." } };
export default function Experts() {
  return <main className="shell expert-profile content-section"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", ...breadcrumbList([{ name: "Eksperci", path: "/eksperci" }]) }) }} /><h1>Eksperci</h1><p>Profile przedstawiają potwierdzone informacje o tożsamości zawodowej. Samo umieszczenie eksperta na tej stronie nie oznacza, że zrecenzował treść serwisu.</p><section className="content-section"><h2>Jak czytać profile ekspertów</h2><ul><li>Profil opisuje tożsamość zawodową osoby na podstawie publicznych źródeł wskazanych w jego treści.</li><li>Recenzja jest przypisana do konkretnych stron i ma własną datę; lista takich stron jest w sekcji „Zweryfikowane treści” w profilu.</li><li>Recenzenci są związani z kliniką Akdeniz Dental prowadzoną przez operatora serwisu, więc nie przedstawiamy ich jako niezależnych ekspertów.</li><li>Obszary pracy opisane przez klinikę nie są tytułami specjalisty.</li></ul><p>Zasady opisują strony <Link className="text-link" href="/weryfikacja-medyczna">Weryfikacja medyczna</Link> i <Link className="text-link" href="/polityka-redakcyjna">Polityka redakcyjna</Link>. Zespół kliniki przedstawia strona <Link className="text-link" href="/nasi-lekarze">Nasi lekarze</Link>.</p></section>{verifiedExperts.map((expert) => <section className="content-section" key={expert.slug}><p className="eyebrow">Recenzent medyczny serwisu</p><h2><Link href={expert.profileUrl}>Lek. dent. {expert.name}</Link></h2><p>{expert.introduction ?? "Dentysta, Antalya, Turcja. Założyciel i właściciel Akdeniz Dental, kliniki prowadzonej przez operatora serwisu."}</p>{expert.reviewScope && <p>{expert.reviewScope}</p>}<p>Profil obejmuje biografię, obszary pracy i publiczne źródła zawodowe. Status recenzji każdej strony jest podany przy jej treści.</p><Link className="text-link" href={expert.profileUrl}>Zobacz profil i źródła →</Link></section>)}<section><h2>Zespół kliniki prowadzonej przez operatora serwisu</h2><p>Poznaj lekarzy Akdeniz Dental, ich wykształcenie i obszary pracy. Obecność w zespole klinicznym nie oznacza recenzji treści serwisu.</p><Link className="text-link" href="/nasi-lekarze">Nasi lekarze →</Link></section><SourceList intro="Profile opierają się na publicznych źródłach zawodowych. Nie stanowią one rekomendacji serwisu ani potwierdzenia recenzji jego treści." sources={Array.from(new Map(verifiedExperts.flatMap((expert) => expert.sources).map((source) => [source.url, { label: source.label, href: source.url }])).values())} /></main>;
}
