/** Clinical biographies supplied by Akdeniz Dental, checked against individual profiles. */
export const TEAM_SOURCE_DATE = "2026-09-30";
export const TEAM_SOURCE_URL = "https://akdenizdental.com/our-team";
export const clinicalTeam = [
  { slug: "mustafa-akca", name: "Mustafa Akça", alternateNames: ["Mustafa Akca"], image: "team-2.jpeg", area: "Protetyka i kompleksowa odbudowa uzębienia", education: "Medipol University, studia stomatologiczne w latach 2012–2018.", focus: "Według kliniki zajmuje się kompleksową odbudową uzębienia, uzupełnieniami cyrkonowymi i planowaniem uśmiechu. Założyciel i właściciel kliniki.", reviewerUrl: "/eksperci/mustafa-akca" },
  { slug: "omer-isen", name: "Ömer İsen", alternateNames: ["Omer Isen", "Omer İsen"], image: "team-5.jpeg", area: "Ortodoncja", education: "Ondokuz Mayıs University: studia stomatologiczne 2012–2017; kształcenie w ortodoncji 2018–2023.", focus: "Według kliniki zajmuje się planowaniem leczenia ortodontycznego. Właściciel kliniki." },
  { slug: "ali-burak-bozkurt", name: "Ali Burak Bozkurt", alternateNames: [], image: "team-1.jpeg", area: "Diagnostyka i planowanie leczenia", education: "Medipol University, studia stomatologiczne w latach 2012–2018.", focus: "Według kliniki zajmuje się diagnostyką stomatologiczną i planowaniem leczenia. Właściciel kliniki." },
  { slug: "mehmet-onur-merey", name: "Mehmet Onur Merey", alternateNames: ["Onur Merey"], image: "team-3.jpeg", reviewerUrl: "/eksperci/mehmet-onur-merey", area: "Chirurgia jamy ustnej i szczękowo-twarzowa", education: "Marmara University: stomatologia 2010–2016; Akdeniz University: kształcenie w chirurgii jamy ustnej i szczękowo-twarzowej 2018–2023.", focus: "Według kliniki zajmuje się implantami, odbudową kości i złożonymi ekstrakcjami. Właściciel kliniki." },
  { slug: "selen-elif-merey", name: "Selen Elif Merey", alternateNames: [], image: "dr-selen.jpeg", area: "Chirurgia jamy ustnej i szczękowo-twarzowa", education: "Hacettepe University: stomatologia 2011–2016; Akdeniz University: kształcenie w chirurgii jamy ustnej i szczękowo-twarzowej 2018–2023.", focus: "Według kliniki zajmuje się chirurgią szczęk i implantologią.", patientMention: { text: "W publicznej opinii pacjenta na Trustpilot z 5 września 2026 r. wymieniona z imienia jako chirurg („surgeon Selen Merey”).", href: "https://www.trustpilot.com/reviews/6a9ba9a141c2778e8b39ba40" } },
  { slug: "mehmet-buyuktarakci", name: "Mehmet Büyüktarakcı", alternateNames: ["Mehmet Büyüktarakçı"], image: "mehmet-buyuktarakci.jpeg", area: "Periodontologia i implantologia", education: "Medipol University: rozpoczęcie studiów stomatologicznych w 2014 r.; Akdeniz University: ukończone studia magisterskie z periodontologii i implantologii. Profil nie podaje dat ukończenia.", focus: "Według kliniki zajmuje się leczeniem przyzębia i implantologią." },
  { slug: "duygu-kolay-toklu", name: "Duygu Kolay Toklu", alternateNames: ["Duygu Kolay"], image: "duygu-kolay.jpeg", area: "Endodoncja", education: "Marmara University: stomatologia 2011–2017; Akdeniz University: studia magisterskie z endodoncji 2019–2024.", focus: "Według kliniki zajmuje się leczeniem kanałowym pod mikroskopem i złożonymi przypadkami endodontycznymi." },
  { slug: "funda-ozen", name: "Funda Özen", alternateNames: [], image: "funda-ozen.jpeg", area: "Protetyka i stomatologia estetyczna", education: "Atatürk University: rozpoczęcie studiów stomatologicznych w 2009 r.; Gaziantep University: ukończenie studiów magisterskich z protetyki w 2016 r.", focus: "Według kliniki zajmuje się licówkami, planowaniem uśmiechu i odbudową protetyczną na implantach." },
  { slug: "ayse-kuskacmaz", name: "Ayşe Kuş Kaçmaz", alternateNames: ["Ayşe Kuş"], image: "ayse-kus.jpeg", area: "Stomatologia estetyczna i protetyka", education: "Süleyman Demirel University, studia stomatologiczne w latach 2015–2020.", focus: "Według kliniki zajmuje się leczeniem estetycznym i odbudową protetyczną.", patientMention: { text: "W publicznej opinii pacjenta na Trustpilot z 5 września 2026 r. wymieniona z imienia jako protetyk („prosthetist Ayşe Kuş”).", href: "https://www.trustpilot.com/reviews/6a9ba9a141c2778e8b39ba40" } },
  { slug: "ozer-ilhan", name: "Özer İlhan", alternateNames: [], image: "ozer-ilhan.jpeg", area: "Stomatologia estetyczna i protetyka", education: "Adnan Menderes University, studia stomatologiczne w latach 2016–2022.", focus: "Według kliniki zajmuje się odbudową protetyczną i cyfrowym planowaniem leczenia.", patientMention: { text: "W publicznej opinii pacjenta na Trustpilot z 6 kwietnia 2026 r. wymieniony z imienia jako lekarz („Dr. Özer Ilhan”).", href: "https://www.trustpilot.com/reviews/69d401b03bafeaa7707e7298" } },
  { slug: "ali-burak-kacmaz", name: "Ali Burak Kaçmaz", alternateNames: [], image: "ali-burak-kacmaz.jpeg", area: "Protetyka i stomatologia estetyczna", education: "Süleyman Demirel University: rozpoczęcie studiów stomatologicznych w 2014 r. Profil potwierdza ukończenie studiów, bez daty ukończenia.", focus: "Według kliniki zajmuje się odbudową protetyczną i leczeniem estetycznym.", patientMention: { text: "W publicznej opinii pacjenta na Trustpilot z 27 lipca 2026 r. wymieniony z imienia jako lekarz prowadzący leczenie koronami („Dr Ali Burak Kacmaz”).", href: "https://www.trustpilot.com/reviews/6a673e626e84afa2c48924db" } },
  { slug: "ayse-boharali", name: "Ayşe Boharalı", alternateNames: [], image: "ayse-boharali.jpeg", area: "Stomatologia estetyczna", education: "Ondokuz Mayıs University, studia stomatologiczne w latach 2017–2022.", focus: "Według kliniki koncentruje się na stomatologii estetycznej i odbudowie protetycznej.", patientMention: { text: "W publicznej opinii pacjentki na Trustpilot z 3 marca 2026 r. wymieniona z imienia jako lekarka prowadząca leczenie („Ayse Boharali”).", href: "https://www.trustpilot.com/reviews/69a5e325167c7ecceebe5010" } },
].map((doctor) => ({ ...doctor, sourceUrl: `https://akdenizdental.com/${doctor.slug}`, imageUrl: `/images/zespol/${doctor.image}` }));
