/** ISO country choices, with Polish labels and Poland first. */
export const countries = [
  {"code": "PL", "label": "Polska"},
  {"code": "AF", "label": "Afganistan"},
  {"code": "AL", "label": "Albania"},
  {"code": "DZ", "label": "Algieria"},
  {"code": "AD", "label": "Andora"},
  {"code": "AO", "label": "Angola"},
  {"code": "AI", "label": "Anguilla"},
  {"code": "AQ", "label": "Antarktyda"},
  {"code": "AG", "label": "Antigua i Barbuda"},
  {"code": "SA", "label": "Arabia Saudyjska"},
  {"code": "AR", "label": "Argentyna"},
  {"code": "AM", "label": "Armenia"},
  {"code": "AW", "label": "Aruba"},
  {"code": "AU", "label": "Australia"},
  {"code": "AT", "label": "Austria"},
  {"code": "AZ", "label": "Azerbejdżan"},
  {"code": "BS", "label": "Bahamy"},
  {"code": "BH", "label": "Bahrajn"},
  {"code": "BD", "label": "Bangladesz"},
  {"code": "BB", "label": "Barbados"},
  {"code": "BE", "label": "Belgia"},
  {"code": "BZ", "label": "Belize"},
  {"code": "BJ", "label": "Benin"},
  {"code": "BM", "label": "Bermudy"},
  {"code": "BT", "label": "Bhutan"},
  {"code": "BY", "label": "Białoruś"},
  {"code": "BO", "label": "Boliwia"},
  {"code": "BA", "label": "Bośnia i Hercegowina"},
  {"code": "BW", "label": "Botswana"},
  {"code": "BR", "label": "Brazylia"},
  {"code": "BN", "label": "Brunei"},
  {"code": "IO", "label": "Brytyjskie Terytorium Oceanu Indyjskiego"},
  {"code": "VG", "label": "Brytyjskie Wyspy Dziewicze"},
  {"code": "BG", "label": "Bułgaria"},
  {"code": "BF", "label": "Burkina Faso"},
  {"code": "BI", "label": "Burundi"},
  {"code": "CL", "label": "Chile"},
  {"code": "CN", "label": "Chiny"},
  {"code": "HR", "label": "Chorwacja"},
  {"code": "CI", "label": "Côte d’Ivoire"},
  {"code": "CW", "label": "Curaçao"},
  {"code": "CY", "label": "Cypr"},
  {"code": "TD", "label": "Czad"},
  {"code": "ME", "label": "Czarnogóra"},
  {"code": "CZ", "label": "Czechy"},
  {"code": "UM", "label": "Dalekie Wyspy Mniejsze Stanów Zjednoczonych"},
  {"code": "DK", "label": "Dania"},
  {"code": "CD", "label": "Demokratyczna Republika Konga"},
  {"code": "DM", "label": "Dominika"},
  {"code": "DO", "label": "Dominikana"},
  {"code": "DJ", "label": "Dżibuti"},
  {"code": "EG", "label": "Egipt"},
  {"code": "EC", "label": "Ekwador"},
  {"code": "ER", "label": "Erytrea"},
  {"code": "EE", "label": "Estonia"},
  {"code": "SZ", "label": "Eswatini"},
  {"code": "ET", "label": "Etiopia"},
  {"code": "FK", "label": "Falklandy"},
  {"code": "FJ", "label": "Fidżi"},
  {"code": "PH", "label": "Filipiny"},
  {"code": "FI", "label": "Finlandia"},
  {"code": "FR", "label": "Francja"},
  {"code": "TF", "label": "Francuskie Terytoria Południowe i Antarktyczne"},
  {"code": "GA", "label": "Gabon"},
  {"code": "GM", "label": "Gambia"},
  {"code": "GS", "label": "Georgia Południowa i Sandwich Południowy"},
  {"code": "GH", "label": "Ghana"},
  {"code": "GI", "label": "Gibraltar"},
  {"code": "GR", "label": "Grecja"},
  {"code": "GD", "label": "Grenada"},
  {"code": "GL", "label": "Grenlandia"},
  {"code": "GE", "label": "Gruzja"},
  {"code": "GU", "label": "Guam"},
  {"code": "GG", "label": "Guernsey"},
  {"code": "GY", "label": "Gujana"},
  {"code": "GF", "label": "Gujana Francuska"},
  {"code": "GP", "label": "Gwadelupa"},
  {"code": "GT", "label": "Gwatemala"},
  {"code": "GN", "label": "Gwinea"},
  {"code": "GW", "label": "Gwinea Bissau"},
  {"code": "GQ", "label": "Gwinea Równikowa"},
  {"code": "HT", "label": "Haiti"},
  {"code": "ES", "label": "Hiszpania"},
  {"code": "NL", "label": "Holandia"},
  {"code": "HN", "label": "Honduras"},
  {"code": "IN", "label": "Indie"},
  {"code": "ID", "label": "Indonezja"},
  {"code": "IQ", "label": "Irak"},
  {"code": "IR", "label": "Iran"},
  {"code": "IE", "label": "Irlandia"},
  {"code": "IS", "label": "Islandia"},
  {"code": "IL", "label": "Izrael"},
  {"code": "JM", "label": "Jamajka"},
  {"code": "JP", "label": "Japonia"},
  {"code": "YE", "label": "Jemen"},
  {"code": "JE", "label": "Jersey"},
  {"code": "JO", "label": "Jordania"},
  {"code": "KY", "label": "Kajmany"},
  {"code": "KH", "label": "Kambodża"},
  {"code": "CM", "label": "Kamerun"},
  {"code": "CA", "label": "Kanada"},
  {"code": "QA", "label": "Katar"},
  {"code": "KZ", "label": "Kazachstan"},
  {"code": "KE", "label": "Kenia"},
  {"code": "KG", "label": "Kirgistan"},
  {"code": "KI", "label": "Kiribati"},
  {"code": "CO", "label": "Kolumbia"},
  {"code": "KM", "label": "Komory"},
  {"code": "CG", "label": "Kongo"},
  {"code": "KR", "label": "Korea Południowa"},
  {"code": "KP", "label": "Korea Północna"},
  {"code": "CR", "label": "Kostaryka"},
  {"code": "CU", "label": "Kuba"},
  {"code": "KW", "label": "Kuwejt"},
  {"code": "LA", "label": "Laos"},
  {"code": "LS", "label": "Lesotho"},
  {"code": "LB", "label": "Liban"},
  {"code": "LR", "label": "Liberia"},
  {"code": "LY", "label": "Libia"},
  {"code": "LI", "label": "Liechtenstein"},
  {"code": "LT", "label": "Litwa"},
  {"code": "LU", "label": "Luksemburg"},
  {"code": "LV", "label": "Łotwa"},
  {"code": "MK", "label": "Macedonia Północna"},
  {"code": "MG", "label": "Madagaskar"},
  {"code": "YT", "label": "Majotta"},
  {"code": "MW", "label": "Malawi"},
  {"code": "MV", "label": "Malediwy"},
  {"code": "MY", "label": "Malezja"},
  {"code": "ML", "label": "Mali"},
  {"code": "MT", "label": "Malta"},
  {"code": "MP", "label": "Mariany Północne"},
  {"code": "MA", "label": "Maroko"},
  {"code": "MQ", "label": "Martynika"},
  {"code": "MR", "label": "Mauretania"},
  {"code": "MU", "label": "Mauritius"},
  {"code": "MX", "label": "Meksyk"},
  {"code": "FM", "label": "Mikronezja"},
  {"code": "MM", "label": "Mjanma (Birma)"},
  {"code": "MD", "label": "Mołdawia"},
  {"code": "MC", "label": "Monako"},
  {"code": "MN", "label": "Mongolia"},
  {"code": "MS", "label": "Montserrat"},
  {"code": "MZ", "label": "Mozambik"},
  {"code": "NA", "label": "Namibia"},
  {"code": "NR", "label": "Nauru"},
  {"code": "NP", "label": "Nepal"},
  {"code": "BQ", "label": "Niderlandy Karaibskie"},
  {"code": "DE", "label": "Niemcy"},
  {"code": "NE", "label": "Niger"},
  {"code": "NG", "label": "Nigeria"},
  {"code": "NI", "label": "Nikaragua"},
  {"code": "NU", "label": "Niue"},
  {"code": "NF", "label": "Norfolk"},
  {"code": "NO", "label": "Norwegia"},
  {"code": "NC", "label": "Nowa Kaledonia"},
  {"code": "NZ", "label": "Nowa Zelandia"},
  {"code": "OM", "label": "Oman"},
  {"code": "PK", "label": "Pakistan"},
  {"code": "PW", "label": "Palau"},
  {"code": "PA", "label": "Panama"},
  {"code": "PG", "label": "Papua-Nowa Gwinea"},
  {"code": "PY", "label": "Paragwaj"},
  {"code": "PE", "label": "Peru"},
  {"code": "PN", "label": "Pitcairn"},
  {"code": "PF", "label": "Polinezja Francuska"},
  {"code": "PR", "label": "Portoryko"},
  {"code": "PT", "label": "Portugalia"},
  {"code": "ZA", "label": "Republika Południowej Afryki"},
  {"code": "CF", "label": "Republika Środkowoafrykańska"},
  {"code": "CV", "label": "Republika Zielonego Przylądka"},
  {"code": "RE", "label": "Reunion"},
  {"code": "RU", "label": "Rosja"},
  {"code": "RO", "label": "Rumunia"},
  {"code": "RW", "label": "Rwanda"},
  {"code": "EH", "label": "Sahara Zachodnia"},
  {"code": "KN", "label": "Saint Kitts i Nevis"},
  {"code": "LC", "label": "Saint Lucia"},
  {"code": "VC", "label": "Saint Vincent i Grenadyny"},
  {"code": "BL", "label": "Saint-Barthélemy"},
  {"code": "MF", "label": "Saint-Martin"},
  {"code": "PM", "label": "Saint-Pierre i Miquelon"},
  {"code": "SV", "label": "Salwador"},
  {"code": "WS", "label": "Samoa"},
  {"code": "AS", "label": "Samoa Amerykańskie"},
  {"code": "SM", "label": "San Marino"},
  {"code": "SN", "label": "Senegal"},
  {"code": "RS", "label": "Serbia"},
  {"code": "SC", "label": "Seszele"},
  {"code": "SL", "label": "Sierra Leone"},
  {"code": "SG", "label": "Singapur"},
  {"code": "SX", "label": "Sint Maarten"},
  {"code": "SK", "label": "Słowacja"},
  {"code": "SI", "label": "Słowenia"},
  {"code": "SO", "label": "Somalia"},
  {"code": "HK", "label": "SRA Hongkong (Chiny)"},
  {"code": "MO", "label": "SRA Makau (Chiny)"},
  {"code": "LK", "label": "Sri Lanka"},
  {"code": "US", "label": "Stany Zjednoczone"},
  {"code": "SD", "label": "Sudan"},
  {"code": "SS", "label": "Sudan Południowy"},
  {"code": "SR", "label": "Surinam"},
  {"code": "SJ", "label": "Svalbard i Jan Mayen"},
  {"code": "SY", "label": "Syria"},
  {"code": "CH", "label": "Szwajcaria"},
  {"code": "SE", "label": "Szwecja"},
  {"code": "TJ", "label": "Tadżykistan"},
  {"code": "TH", "label": "Tajlandia"},
  {"code": "TW", "label": "Tajwan"},
  {"code": "TZ", "label": "Tanzania"},
  {"code": "PS", "label": "Terytoria Palestyńskie"},
  {"code": "TL", "label": "Timor Wschodni"},
  {"code": "TG", "label": "Togo"},
  {"code": "TK", "label": "Tokelau"},
  {"code": "TO", "label": "Tonga"},
  {"code": "TT", "label": "Trynidad i Tobago"},
  {"code": "TN", "label": "Tunezja"},
  {"code": "TR", "label": "Turcja"},
  {"code": "TM", "label": "Turkmenistan"},
  {"code": "TC", "label": "Turks i Caicos"},
  {"code": "TV", "label": "Tuvalu"},
  {"code": "UG", "label": "Uganda"},
  {"code": "UA", "label": "Ukraina"},
  {"code": "UY", "label": "Urugwaj"},
  {"code": "UZ", "label": "Uzbekistan"},
  {"code": "VU", "label": "Vanuatu"},
  {"code": "WF", "label": "Wallis i Futuna"},
  {"code": "VA", "label": "Watykan"},
  {"code": "VE", "label": "Wenezuela"},
  {"code": "HU", "label": "Węgry"},
  {"code": "GB", "label": "Wielka Brytania"},
  {"code": "VN", "label": "Wietnam"},
  {"code": "IT", "label": "Włochy"},
  {"code": "BV", "label": "Wyspa Bouveta"},
  {"code": "CX", "label": "Wyspa Bożego Narodzenia"},
  {"code": "IM", "label": "Wyspa Man"},
  {"code": "SH", "label": "Wyspa Świętej Heleny"},
  {"code": "AX", "label": "Wyspy Alandzkie"},
  {"code": "CK", "label": "Wyspy Cooka"},
  {"code": "VI", "label": "Wyspy Dziewicze Stanów Zjednoczonych"},
  {"code": "HM", "label": "Wyspy Heard i McDonalda"},
  {"code": "CC", "label": "Wyspy Kokosowe"},
  {"code": "MH", "label": "Wyspy Marshalla"},
  {"code": "FO", "label": "Wyspy Owcze"},
  {"code": "SB", "label": "Wyspy Salomona"},
  {"code": "ST", "label": "Wyspy Świętego Tomasza i Książęca"},
  {"code": "ZM", "label": "Zambia"},
  {"code": "ZW", "label": "Zimbabwe"},
  {"code": "AE", "label": "Zjednoczone Emiraty Arabskie"},
];
