import type { PageContent } from "./site";
import { pages, SITE_URL } from "./site";
import { EUR_PLN_RATE, formatEur, formatPln, priceById } from "./pricing";
export const GUIDES_DATE = "2026-09-30";
export const guideCategories = [
  { id: "na-poczatek", label: "Na początek" },
  { id: "metody", label: "Metody leczenia" },
  { id: "koszty", label: "Koszty i budżet" },
  { id: "bezpieczenstwo", label: "Bezpieczeństwo i wybór kliniki" },
  { id: "wyjazd", label: "Wyjazd i opieka po leczeniu" }
];
export const guideCards = [
  { category: "na-poczatek", href: "/poradniki/leczenie-zebow-w-turcji", title: "Leczenie zębów w Turcji: od czego zacząć?", description: "Metody leczenia, koszty, wybór kliniki i przygotowanie do wyjazdu. Najważniejsze pytania przed pierwszą konsultacją." },
  { category: "metody", href: "/implanty", title: "Implanty zębowe w Turcji: kwalifikacja, etapy i koszty", description: "Co ustalić przed leczeniem implantologicznym, jak wygląda planowanie i gojenie oraz jakie elementy powinny znaleźć się w wycenie." },
  { category: "koszty", href: "/koszt", title: "Ile kosztuje leczenie zębów w Turcji?", description: "Ceny poszczególnych zabiegów, czynniki wpływające na wycenę i pytania, które pomagają porównać pełny zakres leczenia." },
  { category: "metody", href: "/poradniki/licowki-czy-korony", title: "Licówki czy korony? Różnice i przygotowanie zębów", description: "Czym różnią się licówki i korony, jak mogą wymagać przygotowania zęba i dlaczego wybór metody zależy od diagnozy." },
  { category: "metody", href: "/korony-cyrkonowe", title: "Korony cyrkonowe w Turcji: zakres leczenia i koszt", description: "Kiedy rozważa się korony, co obejmuje cena pojedynczej pozycji i jakie dodatkowe koszty należy sprawdzić." },
  { category: "metody", href: "/licowki", title: "Licówki w Turcji: materiały, możliwości i alternatywy", description: "Jak rozmawiać o planie estetycznym, czym różnią się materiały i jakie alternatywy warto omówić z lekarzem dentystą." },
  { category: "metody", href: "/cala-szczeka", title: "Odbudowa całej szczęki w Turcji: możliwości i koszty", description: "Dlaczego odbudowa całej szczęki nie oznacza jednego zabiegu i jak zakres leczenia wpływa na etapy oraz wycenę." },
  { category: "metody", href: "/all-on-4", title: "All-on-4 w Turcji: na czym polega leczenie?", description: "Podstawy koncepcji All-on-4, kwalifikacja do leczenia i pytania o plan, materiały oraz opiekę po zabiegu." },
  { category: "koszty", href: "/poradniki/calkowity-koszt-wyjazdu", title: "Całkowity koszt wyjazdu na leczenie zębów do Turcji", description: "Leczenie, loty, nocleg, transfery, diagnostyka i ewentualna kolejna wizyta. Jak przygotować budżet całego wyjazdu." },
  { category: "koszty", href: "/poradniki/pakiety-leczenia-zebow", title: "Pakiety leczenia zębów w Turcji: co obejmuje cena?", description: "Jak sprawdzić zakres pakietu, dodatkowe opłaty i warunki organizacji wyjazdu przed potwierdzeniem rezerwacji." },
  { category: "bezpieczenstwo", href: "/jak-wybrac-klinike", title: "Jak wybrać klinikę stomatologiczną w Turcji?", description: "Co sprawdzić w informacjach o lekarzu, planie leczenia, wycenie i zasadach opieki po powrocie do Polski." },
  { category: "bezpieczenstwo", href: "/opinie", title: "Opinie o leczeniu zębów w Turcji: jak je oceniać?", description: "Jak czytać doświadczenia pacjentów, rozpoznawać treści reklamowe i szukać informacji istotnych dla własnej decyzji." },
  { category: "bezpieczenstwo", href: "/przed-i-po", title: "Zdjęcia przed i po: co pokazują, a czego nie?", description: "Jak interpretować zdjęcia uśmiechu i dlaczego nie zastępują informacji o diagnozie, metodzie leczenia i trwałości efektu." },
  { category: "wyjazd", href: "/antalya", title: "Leczenie zębów w Antalyi: przygotowanie wyjazdu", description: "Jak zaplanować podróż, wizyty i pobyt oraz jakie pytania zadać przed ustaleniem terminu leczenia." },
  { category: "bezpieczenstwo", href: "/poradniki/tureckie-zeby", title: "Tureckie zęby: o co chodzi i czy są dobre?", description: "Skąd bierze się określenie „tureckie zęby”, jakie problemy opisują stomatolodzy i jak ocenić ryzyko leczenia zębów w Turcji przed wyjazdem." },
  { category: "wyjazd", href: "/poradniki/opieka-po-leczeniu", title: "Opieka po leczeniu zębów w Turcji i powrocie do Polski", description: "Jak ustalić zalecenia, wizyty kontrolne, kontakt z kliniką i sposób przekazania dokumentacji po zakończeniu leczenia." }
];
const nhsAbroad = { label: "NHS: lista kontrolna leczenia za granicą (Treatment abroad checklist)", href: "https://www.nhs.uk/using-the-nhs/healthcare-abroad/going-abroad-for-treatment/treatment-abroad-checklist/" };
const conversationTurkeyTeeth = { label: "The Conversation: ryzyka stomatologii kosmetycznej, w tym „Turkey teeth”", href: "https://theconversation.com/veneers-implants-and-agonising-pain-the-risks-of-cosmetic-dentistry-are-nothing-to-smile-about-227687" };
const msz = { label: "MSZ: informacje dla podróżujących do Turcji", href: "https://www.gov.pl/web/turcja/informacje-dla-podrozujacych" };
const ekuz = { label: "Pacjent.gov.pl: zakres EKUZ i leczenie planowane", href: "https://pacjent.gov.pl/europejska-karta-ubezpieczenia-zdrowotnego-ekuz" };
const adaVeneers = { label: "American Dental Association: licówki", href: "https://www.mouthhealthy.org/all-topics-a-z/veneers" };
const adaCrowns = { label: "American Dental Association: korony", href: "https://www.mouthhealthy.org/all-topics-a-z/crowns" };
export const newGuides: Record<string, PageContent> = {
  "leczenie-zebow-w-turcji": {
    slug: "poradniki/leczenie-zebow-w-turcji", title: "Leczenie zębów w Turcji: jak zacząć i zaplanować wyjazd", description: "Od pierwszego pytania do planu leczenia w Antalyi. Wybór metody, wycena w EUR i PLN, dokumenty, możliwe dwa pobyty i opieka po powrocie do Polski.", eyebrow: "Na początek", h1: "Leczenie zębów w Turcji: od czego zacząć?",
    lead: "Zanim wybierzesz lot do Antalyi, ustal, czego potrzebujesz: uzupełnienia braków, odbudowy uszkodzonych zębów czy zmiany wyglądu uśmiechu. To różne cele, które prowadzą do różnych planów i budżetów.",
    answer: "Zacznij od opisania problemu i pytań do lekarza, potem porównaj możliwości leczenia oraz zakres pisemnej wyceny. Dopiero po ustaleniu etapów, liczby pobytów i zasad opieki po powrocie planuj podróż z Polski. Wstępna wycena porządkuje rozmowę, ale nie zastępuje badania ani ostatecznej kwalifikacji.",
    sections: [
      { title: "Jak wybrać właściwy temat do rozmowy", table: { headers: ["Twoje pytanie", "Co warto ustalić"], rows: [["Brakuje mi zęba: czy potrzebuję implantu?", "Możliwości uzupełnienia braku, diagnostyka i część protetyczna."], ["Chcę zmienić wygląd zębów: licówki czy korony?", "Stan własnych zębów, zakres przygotowania i alternatywy."], ["Potrzebuję całej szczęki: czy All-on-4 jest dla mnie?", "Stan uzębienia i kości, liczba łuków, odbudowa tymczasowa i docelowa."]] } },
      { title: "Co napisać w pierwszym zapytaniu", paragraphs: ["Napisz po polsku, jaki problem chcesz rozwiązać, czy dotyczy góry, dołu lub obu łuków i kiedy możesz przyjechać. Zapytaj, jakie informacje są potrzebne do wstępnej wyceny. Nie traktuj zdjęcia uśmiechu jako diagnozy."], bullets: ["Krótki opis potrzeb i najważniejsze pytania.", "Możliwość przyjazdu na jeden lub dwa pobyty, bez zakładania ich długości.", "Prośba o zakres wyceny, walutę, warunki płatności i zmiany planu.", "Dokumentację medyczną przekazuj dopiero wskazanym bezpiecznym kanałem, nie przez publiczny formularz."] },
      { title: "Cena leczenia a budżet pacjenta z Polski", paragraphs: ["Zęby w Turcji nie mają jednej ceny. Oddziel koszt leczenia od lotów, noclegów, transportu i kontroli. Ceny pojedynczych pozycji poniżej pochodzą z istniejącego cennika; nie są ofertą całego uśmiechu ani potwierdzonym pakietem.", "Porównując ofertę z Polski i Turcji, zestaw ten sam zakres: liczbę zębów, materiały, diagnostykę, prace tymczasowe, kontrole i ewentualne dodatkowe zabiegi. Bez dwóch porównywalnych, datowanych wycen nie wyliczamy procentowej oszczędności."] },
      { title: "Najpierw harmonogram, potem bilety", paragraphs: ["Leczenie implantologiczne może wymagać rozdzielenia etapów na dwa pobyty. Nie przenoś liczby dni z historii innego pacjenta na własny plan. Poproś lekarza o terminy zabiegów, kontroli i ocenę możliwości podróży; zostaw miejsce na zmianę planu po badaniu.", "Przed rezerwacją sprawdź wymogi wjazdu dla swojego obywatelstwa i celu pobytu w aktualnych informacjach MSZ. Samo mieszkanie w Polsce nie oznacza polskiego obywatelstwa. Ustal też, czy polisa obejmuje planowane leczenie i jego powikłania; EKUZ nie finansuje leczenia planowanego."] },
      { title: "Jak zweryfikować klinikę i lekarza", paragraphs: ["Sprawdź tożsamość lekarza prowadzącego, miejsce leczenia, zakres odpowiedzialności i sposób kontaktu po powrocie. Serwis współpracuje z Akdeniz Dental w Antalyi. Profil lekarza oraz recenzja konkretnej strony to różne informacje: obecność lekarza w zespole nie oznacza zatwierdzenia każdego poradnika.", "Opinie pacjentów i zdjęcia mogą pomóc przygotować pytania, ale nie potwierdzają Twojej kwalifikacji ani trwałości wyniku. W serwisie materiały przed i po zachowują swoje informacje o zakresie weryfikacji."] },
      { title: "Co ustalić przed powrotem do Polski", bullets: ["Pisemne zalecenia i terminy kontroli właściwe dla Twojego leczenia.", "Dokumentacja zabiegów oraz dane użytych materiałów i systemów.", "Kontakt do kliniki oraz zasady pilnego zgłoszenia i korekt.", "Możliwość kontroli w Polsce i sposób wymiany dokumentacji między lekarzami."] }
    ], faq: [{ question: "Czy mogę zacząć od wiadomości po polsku?", answer: "Tak, formularz pozwala opisać potrzeby po polsku i poprosić o wstępną wycenę. Dostępność obsługi po polsku podczas wizyt oraz tłumaczenia dokumentów ustal osobno przed rezerwacją." }, { question: "Czy jedna podróż wystarczy?", answer: "Nie można tego potwierdzić bez planu. Szczególnie przy implantach kolejne etapy mogą wymagać drugiego pobytu; liczbę wizyt i odstępy ustala lekarz." }], sources: [msz, ekuz, { label: "Akdeniz Dental: zespół kliniki prowadzonej przez operatora serwisu", href: "https://akdenizdental.com/our-team" }]
  },
  "licowki-czy-korony": {
    slug: "poradniki/licowki-czy-korony", title: "Licówki czy korony? Zakres, przygotowanie i koszt w Turcji", description: "Porównaj licówki i korony przed konsultacją: powierzchnia odbudowy, przygotowanie zęba, materiały i ceny z cennika w EUR oraz około PLN.", eyebrow: "Metody leczenia", h1: "Licówki czy korony? Różnice i przygotowanie zębów",
    lead: "Zdjęcie wymarzonego uśmiechu nie wyjaśnia, jaka odbudowa jest odpowiednia dla Twoich zębów. Zanim porównasz cenę, poproś lekarza o uzasadnienie metody i opis przygotowania każdego zęba.",
    answer: "Licówka obejmuje przede wszystkim przednią powierzchnię zęba, a korona otacza jego część widoczną ponad dziąsłem. To inny zakres odbudowy i przygotowania. Wybór zależy od stanu zęba, wcześniejszego leczenia, zgryzu i celu terapii. Sama nazwa materiału, np. cyrkon lub E-max, nie wystarcza do rozpoznania rodzaju pracy.",
    sections: [
      { title: "Porównanie zakresu: nie tylko kolor uśmiechu", table: { headers: ["Pytanie", "Licówka", "Korona"], rows: [["Co obejmuje?", "Głównie przednią powierzchnię zęba.", "Odbudowę otaczającą ząb."], ["Co trzeba zbadać?", "Stan szkliwa i dziąseł, zgryz, oczekiwania.", "Ilość i stan pozostałych tkanek zęba, wcześniejsze leczenie, zgryz."], ["Co potwierdzić w ofercie?", "Materiał, technikę, liczbę zębów i przygotowanie.", "Zastosowanie na własnym zębie lub implancie oraz leczenie przygotowawcze."]] } },
      { title: "Przygotowanie zęba i odwracalność", paragraphs: ["Przygotowanie do licówki może wymagać usunięcia części szkliwa; po jego usunięciu leczenia nie można traktować jako odwracalnej zmiany wyglądu. Korona ma inny zakres i również wymaga omówienia przygotowania zęba. Poproś o opis proponowanej ingerencji zamiast przyjmować obietnicę „bez szlifowania” dla wszystkich zębów.", "Próchnica lub choroba dziąseł wymagają oceny przed odbudową. Zapytaj, czy istnieje mniej inwazyjna alternatywa i dlaczego lekarz proponuje daną metodę w Twoim przypadku."] },
      { title: "Co naprawdę porównujesz w cenniku", paragraphs: ["Korona cyrkonowa i licówka kompozytowa są osobnymi pozycjami. Nie porównuj ich wyłącznie jako dwóch cen za biały ząb: materiał i zakres pracy są inne. Odbudowa E-max określa materiał, a pozycja „Veneer kuron” wymaga doprecyzowania, czy chodzi o koronę, czy o inną odbudowę.", "Podane ceny nie obejmują automatycznie leczenia kanałowego, korekt zgryzu ani wszystkich przygotowań. Ostateczna wycena powinna wskazywać zęby, materiały i zakres dodatkowych czynności."] },
      { title: "Pytania przed zgodą na leczenie", bullets: ["Dlaczego dla tego zęba proponowana jest licówka albo korona?", "Ile własnych tkanek będzie przygotowane i jakie są alternatywy?", "Jakie ryzyko, ograniczenia i konieczność późniejszej wymiany trzeba omówić?", "Jak zostaną sprawdzone dopasowanie i zgryz przed zakończeniem wizyty?", "Kto wykona kontrolę po powrocie do Polski i jak przekażę dokumentację?"] }
    ], faq: [{ question: "Czym różni się korona cyrkonowa od licówki?", answer: "Cyrkon to materiał, a korona to rodzaj odbudowy. Licówka ma inny zakres. W planie należy podać zarówno materiał, jak i dokładny rodzaj pracy." }, { question: "Czy mogę wybrać metodę tylko na podstawie ceny?", answer: "Cena może pomóc w planowaniu budżetu, ale nie określa kwalifikacji. Najpierw lekarz powinien ocenić zęby i omówić alternatywy, przygotowanie oraz ryzyko." }, { question: "Jak długo trzymają licówki?", answer: "Nie podajemy liczby lat. Licówki nie są dożywotnie i mogą wymagać późniejszej wymiany; czas użytkowania zależy od materiału, przygotowania zęba, higieny i kontroli. Pytaj o to lekarza przed zgodą na leczenie." }, { question: "Jakie są minusy licówek?", answer: "Przygotowanie zęba może wymagać usunięcia części szkliwa, czego nie można cofnąć. Licówki mogą też wymagać wymiany, a efekt zależy od stanu zębów i dziąseł. Poproś o opis przygotowania i alternatyw." }, { question: "Czy zęby pod licówkami się psują?", answer: "Mogą, jeśli nie są dobrze ocenione, przygotowane i pielęgnowane. Licówki nie chronią przed próchnicą, a próchnica i choroby dziąseł wymagają oceny przed odbudową; higiena i kontrole nadal są potrzebne." }], sources: [adaVeneers, adaCrowns]
  },
  "calkowity-koszt-wyjazdu": {
    slug: "poradniki/calkowity-koszt-wyjazdu", title: "Całkowity koszt leczenia zębów w Turcji: budżet wyjazdu", description: "Zaplanuj budżet leczenia w Antalyi: cennik EUR/PLN, loty, hotel, transfery, dwa pobyty, dodatkowe zabiegi i kontrole po powrocie do Polski.", eyebrow: "Koszty i budżet", h1: "Całkowity koszt wyjazdu na leczenie zębów do Turcji",
    lead: "Cena zabiegu to tylko jedna część budżetu. Zanim wpłacisz zaliczkę, zestaw koszty każdego pobytu i sprawdź, które elementy potwierdza oferta kliniki, a które organizujesz samodzielnie.",
    answer: "Budżet całego wyjazdu obejmuje potwierdzone leczenie, podróż, noclegi, transport, ewentualny drugi pobyt oraz kontrole i możliwe korekty. Nie znamy jednej ceny pakietu dla każdego pacjenta. Do kalkulacji używaj indywidualnej wyceny oraz aktualnych ofert podróży; sam cennik implantów lub koron nie daje ceny końcowej.",
    sections: [
      { title: "Lista kosztów do uzupełnienia własnymi ofertami", table: { headers: ["Pozycja", "Co wpisać do budżetu", "Co potwierdzić"], rows: [["Leczenie", "Kwotę pisemnej wyceny w EUR.", "Zęby, implanty, łączniki, prace tymczasowe i docelowe."], ["Diagnostyka i przygotowanie", "Kwoty z planu lub pozycji dodatkowych.", "Badania, ekstrakcje, leczenie kanałowe, ewentualna odbudowa kości."], ["Loty z Polski", "Ofertę dla realnych terminów i liczby osób.", "Bagaż, zmiana biletu i ewentualny drugi przelot."], ["Noclegi", "Liczbę nocy razy potwierdzoną stawkę.", "Osobę towarzyszącą, posiłki i przedłużenie pobytu."], ["Transfery", "Transport lotnisko, hotel i klinika.", "Które przejazdy są w ofercie, a które płatne osobno."], ["Powrót i kontrole", "Koszty uzgodnionych kontroli i ewentualnej podróży.", "Kto odpowiada za korekty i ponowny wyjazd."], ["Polisa i rezerwa", "Kwoty z polisy oraz własną rezerwę.", "Wyłączenia planowanego leczenia i zmian harmonogramu."]] } },
      { title: "Jak policzyć jeden i dwa pobyty", paragraphs: ["Dla jednego pobytu zsumuj potwierdzoną cenę leczenia, lot, nocleg, transport i kontrolę. Dla dwóch pobytów dopisz drugie bilety, noclegi i przejazdy, nawet jeśli klinika rozlicza leczenie w jednej kwocie. Nie licz ponownie usług, które są już wyraźnie wliczone.", "Odstępu pomiędzy wizytami i długości pobytu nie ustalaj na podstawie ceny biletu. Harmonogram wynika z planu leczenia i może zmienić się po badaniu. Poproś o zasady zmiany rezerwacji i koszt dodatkowych dni."] },
      { title: "EUR, PLN i koszt płatności", paragraphs: ["Kwoty w PLN przy cenniku są przeliczeniem orientacyjnym. Do budżetu płatności wpisz również ewentualną prowizję banku lub operatora i sprawdź walutę, w której rzeczywiście rozliczysz ofertę. Nie przeliczaj całego wyjazdu jednym kursem, jeśli lot i hotel kupujesz w innej walucie.", "Nie publikujemy niepotwierdzonych stawek za loty i hotel ani jednej sumy All-on-4. Zweryfikowane pozycje cennika można wykorzystać do omówienia zakresu, ale brakujące elementy muszą zostać wycenione."] },
      { title: "Turcja a Polska: jak porównać oferty", paragraphs: ["Zbierz dwie datowane wyceny dla tego samego rozpoznania, liczby zębów, materiałów i prac tymczasowych. Do oferty z Turcji dodaj koszty podróży oraz organizacji kontroli. Do każdej oferty dopisz wyłączenia i warunki zmiany planu.", "Nie podajemy średniej ceny leczenia w Polsce ani procentu oszczędności bez źródła i porównywalnego zakresu. Różnica ceny pojedynczej korony nie jest automatycznie różnicą kosztu całego leczenia."] },
      { title: "Dokumenty i polisa też mają znaczenie dla budżetu", paragraphs: ["Przed rezerwacją sprawdź aktualne zasady wjazdu w informacjach MSZ, uwzględniając obywatelstwo i cel wyjazdu. EKUZ nie jest finansowaniem planowanego leczenia. Zakres polisy podróżnej, leczenie powikłań oraz koszty przedłużenia pobytu trzeba potwierdzić z ubezpieczycielem."] }
    ], faq: [{ question: "Czy 450 EUR za implant oznacza cały odbudowany ząb?", answer: "Nie można tego założyć. Cena pozycji Implant Aiser nie potwierdza włączenia łącznika, korony, badań ani dodatkowych zabiegów. Pełny zakres musi określać indywidualna oferta." }, { question: "Czy hotel i transfer są zawsze w cenie?", answer: "Nie. Uwzględniaj je jako wliczone tylko wtedy, gdy oferta podaje konkretny zakres, liczbę nocy, przejazdy i warunki dodatkowych opłat." }, { question: "Ile kosztuje 6 implantów zębowych i ile wyniesie cały wyjazd?", answer: `Same implanty to arytmetyczna suma pozycji z cennika: 6 × ${formatEur(priceById("aiser").eur)} to ${formatEur(priceById("aiser").eur * 6)}, orientacyjnie ${formatPln(priceById("aiser").eur * 6)} przy kursie 1 EUR = ${EUR_PLN_RATE.toFixed(2).replace(".", ",")} PLN. To nie jest cena kompletnego leczenia: cena implantu nie potwierdza łączników, koron, diagnostyki ani dodatkowych zabiegów. Do budżetu wyjazdu dolicz podróż, noclegi, kontrole i możliwy drugi pobyt.` }], sources: [msz, ekuz]
  },
  "tureckie-zeby": {
    slug: "poradniki/tureckie-zeby", published: "2026-10-03", lastUpdated: "2026-10-03", title: "Tureckie zęby: o co chodzi, jakie są problemy i jak je ocenić", description: "Co znaczy „tureckie zęby”, czy są dobre, jakie problemy opisują stomatolodzy i jak ocenić ryzyko leczenia zębów w Turcji, zanim kupisz bilet.", eyebrow: "Bezpieczna decyzja", h1: "Tureckie zęby: o co chodzi i czy są dobre?",
    lead: "„Tureckie zęby” to potoczne określenie, które upowszechniło się w brytyjskich mediach społecznościowych. Zamiast oceniać cały kraj jednym zdaniem, pokazujemy, skąd biorą się obawy i co można sprawdzić przed wyjazdem.",
    answer: "„Tureckie zęby” to potoczne określenie leczenia stomatologicznego, zwykle licówek, wykonanego w Turcji. Jakość zależy od lekarza, planu, materiałów i opieki po zabiegu, a nie od kraju. Ryzyko rośnie, gdy brakuje diagnostyki, dokumentacji i możliwości kontroli.",
    sections: [
      { title: "O co chodzi z „tureckimi zębami”?", paragraphs: ["Określenie opisuje leczenie estetyczne, najczęściej licówki, wykonane za granicą w niższej cenie. W mediach społecznościowych krąży wiele nagrań i zdjęć z różnymi przypadkami, dlatego pojedynczy materiał nie pozwala ocenić ani kliniki, ani kraju.", "Nazwa nie oznacza jednego zabiegu ani jednej jakości leczenia. Dla pacjenta ważniejsze od hasła jest pytanie, jaka konkretnie praca ma być wykonana, na których zębach i w jakim planie."] },
      { title: "Czy tureckie zęby są dobre?", paragraphs: ["Na to pytanie nie da się odpowiedzieć jednym zdaniem dla całego kraju. O jakości decydują lekarz, diagnostyka, plan, materiały, wykonanie i kontrole, a te elementy można sprawdzić w konkretnej klinice, zanim wpłacisz zaliczkę. Brytyjska służba zdrowia (NHS) radzi opierać decyzję o leczeniu za granicą na jakości opieki, a nie na atrakcyjności miejsca wyjazdu.", "Listę pytań do kliniki znajdziesz w poradniku o wyborze kliniki stomatologicznej w Turcji, a zasady czytania opinii na stronie o opiniach pacjentów."] },
      { title: "Jakie są problemy z tureckimi zębami?", paragraphs: ["Autorzy artykułu o ryzykach stomatologii kosmetycznej opisują, że licówki zwykle wymagają usunięcia części szkliwa, a nieprawidłowe przygotowanie zęba zwiększa jego podatność na próchnicę. Źle dopasowana licówka może też sprzyjać gromadzeniu się płytki i resztek pokarmu, a w efekcie nieprzyjemnemu zapachowi z ust, przebarwieniom, próchnicy i chorobom dziąseł.", "Te ryzyka dotyczą leczenia w każdym kraju. Za granicą trudniej bywa je naprawić, gdy po powrocie brakuje dokumentacji, informacji o użytych materiałach albo ustalonej osoby do kontaktu. Dlatego poproś o plan na piśmie, opis przygotowania zębów i zasady kontroli."] },
      { title: "Czy leczenie „w tydzień” jest bezpieczne?", paragraphs: ["Krótki pobyt nie jest sam w sobie wadą ani zaletą. O czasie decyduje plan: etapy, gojenie, wykonanie prac i kontrola. Nie rezerwuj lotów, zanim lekarz potwierdzi harmonogram i możliwy drugi pobyt, i nie zakładaj, że liczba dni z cudzej historii dotyczy Ciebie.", "NHS zwraca uwagę, by po zabiegu pozostać w kraju leczenia przez czas wystarczający na regenerację przed podróżą powrotną i ustalić z kliniką sposób opieki po leczeniu."] },
      { title: "Ile wytrzymują zęby z Turcji?", paragraphs: ["Nie podajemy liczby lat. Trwałość zależy od rodzaju pracy, materiału, przygotowania zęba, higieny, zgryzu i regularnych kontroli, a nie od kraju. Licówki i korony nie są dożywotnie i mogą wymagać późniejszej wymiany.", "Zapytaj o pisemne warunki gwarancji i wymagane kontrole. Gwarancja nie zastępuje planu kontroli i nie gwarantuje wyniku."] },
      { title: "Co zrobić, gdy po powrocie coś niepokoi?", paragraphs: ["Najpierw skontaktuj się z kliniką i przekaż dokumentację oraz zdjęcia. Przy pilnych objawach, takich jak silny ból, obrzęk lub gorączka, szukaj pomocy lokalnie. Polski dentysta może ocenić sytuację, ale potrzebuje dokumentacji i informacji o materiałach, a przejęcie opieki nie jest automatyczne.", "Szczegóły o kontrolach, korekcie i zgłoszeniach znajdziesz w poradniku o opiece po leczeniu oraz na stronie o reklamacjach."] }
    ],
    faq: [
      { question: "O co chodzi z tureckimi zębami?", answer: "To potoczne określenie leczenia stomatologicznego, najczęściej licówek, wykonanego w Turcji. Nie oznacza jednego zabiegu ani jednej jakości leczenia, dlatego liczy się konkretny plan i klinika." },
      { question: "Czy tureckie zęby są dobre?", answer: "Nie da się tego ocenić dla całego kraju. Jakość zależy od lekarza, diagnostyki, planu, materiałów i opieki po zabiegu, które można sprawdzić w konkretnej klinice przed wpłatą zaliczki." },
      { question: "Jakie są problemy z tureckimi zębami?", answer: "Opisywane ryzyka to nieprawidłowo przygotowany ząb, źle dopasowane licówki lub korony, próchnica i choroby dziąseł. Dotyczą leczenia w każdym kraju, a za granicą utrudnia je brak dokumentacji i kontroli po powrocie." },
      { question: "Ile wytrzymują zęby z Turcji?", answer: "Nie podajemy liczby lat. Trwałość zależy od rodzaju pracy, materiału, higieny, zgryzu i kontroli, a nie od kraju, a licówki i korony mogą wymagać późniejszej wymiany." }
    ],
    sources: [nhsAbroad, conversationTurkeyTeeth, adaVeneers]
  },
  "pakiety-leczenia-zebow": {
    slug: "poradniki/pakiety-leczenia-zebow", title: "Pakiety leczenia zębów w Turcji: zakres ceny i opłaty", description: "Sprawdź pakiet leczenia w Antalyi przed rezerwacją: materiały, etapy, hotel i transfery, wyłączenia, zaliczka i opieka po powrocie do Polski.", eyebrow: "Koszty i budżet", h1: "Pakiety leczenia zębów w Turcji: co obejmuje cena?",
    lead: "Słowo „pakiet” nie określa zakresu leczenia ani podróży. Poproś o listę usług z podziałem na wliczone, dodatkowo płatne i jeszcze nieustalone, zanim porównasz oferty.",
    answer: "Pakiet można ocenić dopiero po sprawdzeniu liczby zębów i implantów, materiałów, prac tymczasowych, badań, wizyt oraz zasad opieki. Hotel, transfery, loty i pomoc po polsku nie są automatycznie wliczone. Na tej stronie nie przedstawiamy niepotwierdzonego pakietu Akdeniz Dental jako gotowej oferty sprzedaży.",
    sections: [
      { title: "Trzy rubryki, które porządkują ofertę", table: { headers: ["Status", "Przykład pytania", "Czego oczekiwać"], rows: [["Wliczone", "Czy konkretna praca docelowa i tymczasowa są w tej kwocie?", "Opis, liczba, materiał i potwierdzenie ceny."], ["Płatne dodatkowo", "Ile kosztuje dodatkowy zabieg lub nocleg?", "Stawka, jednostka i warunki naliczania."], ["Do ustalenia", "Co zmieni się, jeśli badanie wykaże inną potrzebę?", "Zasady aktualizacji planu i zgody na koszt."]] } },
      { title: "Zakres kliniczny: co oznacza ta liczba zębów", bullets: ["Liczba leczonych zębów lub łuków i rozpoznanie, którego dotyczy plan.", "Marka implantów, łączniki, materiał i rodzaj pracy protetycznej.", "Diagnostyka, przygotowanie i możliwe dodatkowe zabiegi.", "Rozróżnienie odbudowy tymczasowej i ostatecznej.", "Liczba wizyt, kontrole i warunki zmiany planu po badaniu."] },
      { title: "Hotel, lot, transfer i komunikacja po polsku", paragraphs: ["Sprawdź nazwę i standard zakwaterowania, liczbę nocy, dopłatę za osobę towarzyszącą i zasady przedłużenia pobytu. Dla transferów ustal konkretne trasy. Lot uwzględnij jako część pakietu tylko wtedy, gdy oferta rzeczywiście go zawiera.", "Formularz i poradniki są po polsku. To nie jest potwierdzenie stałej dostępności tłumacza w gabinecie. Przed rezerwacją zapytaj o komunikację z lekarzem, język dokumentów i sposób omówienia świadomej zgody."] },
      { title: "Zaliczka, płatność i zmiana planu", paragraphs: ["Poproś o pisemny termin ważności oferty, walutę, harmonogram płatności i zasady anulowania lub zmiany rezerwacji. Nie publikujemy jednej wysokości zaliczki ani warunków zwrotu, których nie potwierdzono dla Twojej oferty.", "Jeżeli lekarz zmieni plan po badaniu, nowy zakres i koszt powinny zostać omówione przed zgodą na dalsze leczenie. Nie utożsamiaj cennika pojedynczych pozycji z umową na cały wyjazd."] },
      { title: "Gwarancja nie zastępuje planu kontroli", paragraphs: ["Ustal na piśmie zakres odpowiedzialności, wyłączenia, wymagane kontrole i koszty ponownej podróży. Samo hasło „gwarancja” nie mówi, czy obejmuje korektę, pracę protetyczną, nocleg lub lot. Poproś również o sposób zgłoszenia problemu po powrocie do Polski."] }
    ], faq: [{ question: "Czy All-on-4 w pakiecie oznacza oba łuki?", answer: "Nie musi. Oferta powinna podawać jeden lub dwa łuki, liczbę implantów, rodzaj pracy tymczasowej i docelowej oraz wszystkie wyłączenia." }, { question: "Czy lista cen jest ofertą pakietową?", answer: "Nie. Cennik podaje kwoty za nazwane pozycje. Pełny pakiet wymaga odrębnej wyceny, rozpoznania, harmonogramu i potwierdzenia usług wliczonych." }], sources: [{ label: "Cennik kliniki: 24 pozycje, zakres i data", href: `${SITE_URL}/koszt#cennik` }]
  },
  "opieka-po-leczeniu": {
    slug: "poradniki/opieka-po-leczeniu", title: "Opieka po leczeniu zębów w Turcji: powrót i kontrole", description: "Co ustalić przed powrotem do Polski: dokumentacja, kontrole implantów i odbudów, kontakt z kliniką, korekty i pomoc w pilnych sytuacjach.", eyebrow: "Wyjazd i opieka po leczeniu", h1: "Opieka po leczeniu zębów w Turcji i powrocie do Polski",
    lead: "Plan nie kończy się na ostatniej wizycie w Antalyi. Jeszcze przed wyjazdem ustal, kto odpowie na pytania po powrocie i jak zorganizujesz kontrolę oraz przekazanie dokumentacji lekarzowi w Polsce.",
    answer: "Przed powrotem odbierz pisemne zalecenia, opis zabiegów, dane materiałów i systemów oraz terminy kontroli. Potwierdź kontakt do kliniki i zasady korekt, również gdy wymagają kolejnego pobytu. Zdalna wiadomość nie zastępuje badania. Przy pilnych objawach szukaj pomocy na miejscu, zamiast czekać na odpowiedź lub lot do Turcji.",
    sections: [
      { title: "Dokumentacja, którą warto odebrać", bullets: ["Opis rozpoznania, wykonanych zabiegów i leczonych zębów lub łuków.", "Dane lekarza, daty leczenia oraz kopie dostępnych badań.", "Dane implantów i elementów protetycznych, jeżeli były zastosowane.", "Opis pracy tymczasowej i docelowej oraz kolejnych etapów.", "Pisemne zalecenia, terminy kontroli i zasady zgłoszenia problemu.", "Warunki gwarancji lub reklamacji, jeżeli stanowią część umowy."] },
      { title: "Kontrola w Polsce: ustal możliwość przed leczeniem", paragraphs: ["Przed rezerwacją porozmawiaj z lekarzem w Polsce o możliwości późniejszej kontroli i wymaganej dokumentacji. Nie zakładaj automatycznego przejęcia opieki ani serwisu każdego systemu implantologicznego. Zasady i koszt lokalnej wizyty ustal z konkretnym gabinetem.", "Dla kolejnych etapów leczenia w Antalyi potwierdź, jakie informacje trzeba przesłać, kto podejmuje decyzję i kiedy konieczna jest wizyta osobista. Terminy oraz zalecenia powinny wynikać z Twojego planu, nie z ogólnego harmonogramu w internecie."] },
      { title: "Codzienna pielęgnacja i ograniczenia", paragraphs: ["Poproś lekarza o zalecenia dopasowane do zabiegu, materiałów i aktualnego etapu gojenia, w tym dotyczące higieny, jedzenia i aktywności. Nie stosuj instrukcji dla licówek jako zaleceń po zabiegu implantologicznym.", "Licówki również wymagają higieny i kontroli; nie chronią automatycznie przed próchnicą. Niepokojące dopasowanie zgryzu, uszkodzenie lub poluzowanie odbudowy zgłoś lekarzowi. Nie próbuj samodzielnie przyklejać pracy protetycznej."] },
      { title: "Kiedy nie czekać na kontakt z kliniką", paragraphs: ["Narastający ból, obrzęk lub gorączka wymagają pilnej oceny stomatologicznej. Jeśli masz trudności z oddychaniem lub połykaniem, szukaj natychmiastowej pomocy ratunkowej. Formularz wyceny nie jest kanałem pomocy w nagłych sytuacjach.", "Po pilnej ocenie przekaż klinice dokumentację wskazanym bezpiecznym kanałem. Decyzji o ponownym locie nie podejmuj zamiast uzyskania potrzebnej pomocy na miejscu."] },
      { title: "Korekta, reklamacja i kolejny wyjazd", paragraphs: ["Ustal, kto ocenia zgłoszenie i jakie dokumenty są wymagane. Oddziel koszt zabiegu od kosztów podróży, hotelu i kontroli. Nie zakładaj, że ponowny przelot lub opieka w Polsce są objęte ceną.", "Jeżeli potrzebny jest kolejny pobyt, uzgodnij zakres wizyty i możliwość podróży z lekarzem. Zachowaj wycenę, zgody, zalecenia oraz korespondencję dotyczącą zmian planu."] }
    ], faq: [{ question: "Czy konsultacja na WhatsApp zastąpi kontrolę?", answer: "Nie. Kontakt zdalny może pomóc przekazać informacje, ale nie zastępuje badania, gdy lekarz uzna je za konieczne. Pilnej pomocy szukaj lokalnie." }, { question: "Czy kontrola w Polsce jest w cenie leczenia?", answer: "Nie można tego założyć. Zakres kontroli, gabinet i koszty wymagają odrębnego potwierdzenia przed leczeniem." }], sources: [adaVeneers, { label: "NHS: objawy wymagające pilnej pomocy stomatologicznej", href: "https://www.nhs.uk/conditions/dental-abscess/" }]
  }
};
for (const guide of Object.values(newGuides)) { guide.published ??= GUIDES_DATE; guide.lastUpdated ??= GUIDES_DATE; guide.schemaType = "MedicalWebPage"; }
export const GUIDES_LATEST_DATE = Object.values(newGuides).map((guide) => guide.lastUpdated!).reduce((a, b) => (a > b ? a : b));
export const allGuidePages = [...Object.values(newGuides), ...guideCards.filter((card) => !card.href.startsWith("/poradniki/")).map((card) => pages[card.href.slice(1)])];
export function guideHref(path: string, source: string) { return `${path}${path.includes("?") ? "&" : "?"}guide_source=${encodeURIComponent(source)}`; }
export function guideAssessmentHref(source: string, location: string) { return `/kontakt?lead_source=OGZ-PL&cta_location=${location}&page_path=${encodeURIComponent(source)}&guide_source=${encodeURIComponent(source)}`; }
