import type { PageContent } from "./site";
import { OPERATOR } from "./operator";

const NAME = OPERATOR.legalName ?? "operator serwisu";
const ADDRESS = OPERATOR.streetAddress ? [OPERATOR.streetAddress, [OPERATOR.postalCode, OPERATOR.locality].filter(Boolean).join(" "), OPERATOR.region, OPERATOR.country].filter(Boolean).join(", ") : "adres podany na stronie „O serwisie”";
const EMAIL = OPERATOR.email ?? "adres e-mail podany na stronie kontaktowej";
const VERSION = "Obecna wersja obowiązuje od 2 października 2026 r.";

/**
 * Legal pages (v2, after independent review). Drafted to protect the operator within mandatory consumer and
 * data-protection law. A Polish and a Turkish lawyer must confirm them before LEGAL_REVIEW_CONFIRMED_DATE is set
 * (see docs/consent-and-data-handling.md). Do not add statements about operator practices that are not verified.
 */
export const legalPages: Record<string, PageContent> = {
  regulamin: {
    slug: "regulamin", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Regulamin serwisu",
    description: "Regulamin serwisu Zęby w Turcji: charakter informacyjny, ryzyka i brak gwarancji, formularz, ceny orientacyjne, odpowiedzialność, reklamacje i prawo właściwe.",
    eyebrow: "Dokument prawny", h1: "Regulamin serwisu", lead: "Serwis ma charakter informacyjny. Treści nie są diagnozą, wiążącą ofertą ani umową o świadczenie usług medycznych.",
    answer: `Serwis prowadzi ${NAME}. Treści mają charakter informacyjny, nie są diagnozą ani wiążącą ofertą, a o leczeniu decyduje lekarz po badaniu. Zapytanie z formularza nie jest umową o leczenie ani gwarancją wyniku.`,
    sections: [
      { title: "1. Postanowienia ogólne", paragraphs: [`1.1. Serwis leczeniezebowwturcji.pl („Serwis”) prowadzi ${NAME}, ${ADDRESS} („Operator”). Operator prowadzi także klinikę Akdeniz Dental w Antalyi („Klinika”). Kontakt: ${EMAIL}.`, "1.2. Regulamin określa zasady korzystania z Serwisu i jest dostępny nieodpłatnie na stronie, w formie umożliwiającej jego pobranie, utrwalenie i wydrukowanie. Użytkownikiem jest każda osoba korzystająca z Serwisu; konsumentem jest użytkownik będący osobą fizyczną działającą w celu niezwiązanym z jej działalnością gospodarczą lub zawodową.", "1.3. Korzystanie z Serwisu oznacza akceptację Regulaminu w zakresie usług elektronicznych opisanych poniżej. Jeżeli nie akceptujesz Regulaminu, zaprzestań korzystania z Serwisu."] },
      { title: "2. Usługi elektroniczne i wymagania techniczne", paragraphs: ["2.1. Operator świadczy nieodpłatnie dwie usługi elektroniczne: udostępnianie treści informacyjnych oraz przyjmowanie zapytań przez formularz kontaktowy. Umowa o ich świadczenie zostaje zawarta z chwilą rozpoczęcia korzystania i może zostać zakończona w każdej chwili przez zaprzestanie korzystania.", "2.2. Do korzystania z Serwisu potrzebne są urządzenie z dostępem do internetu, aktualna przeglądarka z włączoną obsługą JavaScript oraz, dla formularza, adres e-mail lub numer telefonu.", "2.3. Korzystanie z internetu wiąże się z typowymi zagrożeniami, takimi jak złośliwe oprogramowanie, wyłudzanie danych czy podszywanie się pod nadawcę. Operator nie prosi o hasła ani dane płatnicze przez formularz; wątpliwe wiadomości weryfikuj, kontaktując się z Operatorem na adres z sekcji 1."] },
      { title: "3. Charakter treści i brak relacji lekarz–pacjent", bullets: ["treści mają charakter ogólny, informacyjny i edukacyjny; mogą zawierać informację handlową o usługach Kliniki, oznaczoną jako taka", "korzystanie z Serwisu nie tworzy relacji lekarz–pacjent; relację tę nawiązuje dopiero badanie w Klinice", "wstępna ocena jest orientacyjną informacją organizacyjno-handlową na podstawie danych podanych w zapytaniu; nie stanowi diagnozy ani porady lekarskiej i nie zastępuje badania", "materiały nie służą do samodzielnej diagnozy ani do podejmowania decyzji o leczeniu bez badania; decyzję medyczną podejmuje lekarz po badaniu i uzyskaniu pełnych informacji o stanie zdrowia", "w stanach nagłych zagrażających zdrowiu lub życiu skontaktuj się z numerem alarmowym 112 lub lokalną służbą ratunkową; Serwis nie jest do tego przeznaczony"] },
      { title: "4. Ryzyka i brak gwarancji", paragraphs: ["4.1. Każdy zabieg stomatologiczny, w tym implantologiczny, protetyczny i chirurgiczny, wiąże się z ryzykiem powikłań, na przykład bólu, obrzęku, krwawienia, zakażenia, nieprzyjęcia się implantu, konieczności korekty lub powtórzenia zabiegu. Ryzyko omawia lekarz przed zabiegiem.", "4.2. Powodzenie leczenia zależy także od stanu zdrowia, higieny, palenia tytoniu oraz przestrzegania zaleceń i terminów kontroli. Wyniki są indywidualne; zdjęcia, opisy i opinie mają charakter ilustracyjny i nie gwarantują takiego samego rezultatu u innej osoby.", "4.3. Serwis nie zawiera gwarancji rezultatu leczenia ani gwarancji jakości w rozumieniu przepisów. Ewentualna gwarancja wymaga odrębnego dokumentu z jej warunkami i wymaganymi kontrolami.", "4.4. Leczenie bywa wieloetapowe i wymaga kilku wizyt. Przed podróżą po zabiegu zapytaj lekarza o zalecenia dotyczące lotu i rozważ ubezpieczenie podróżne obejmujące koszty leczenia powikłań. Koszty dodatkowych podróży i leczenia kontynuowanego w Polsce mogą obciążać pacjenta, o ile umowa lub bezwzględnie obowiązujące przepisy nie stanowią inaczej."] },
      { title: "5. Ceny i oferta", paragraphs: ["5.1. Ceny, kursy walut i zakres świadczeń w Serwisie są orientacyjne, mają datę aktualizacji i nie stanowią oferty w rozumieniu Kodeksu cywilnego, lecz zaproszenie do zawarcia umowy.", "5.2. Wiążący plan leczenia, cena, harmonogram i warunki płatności wynikają wyłącznie z pisemnej oferty lub umowy Kliniki zawartej po badaniu. Plan i cena mogą się zmienić po badaniu klinicznym i diagnostyce. Zakres ewentualnej koordynacji transferów i zakwaterowania oraz odpowiedzialność za nie określa umowa."] },
      { title: "6. Formularz kontaktowy", bullets: ["wysłanie formularza jest dobrowolne i służy uzyskaniu bezpłatnej wstępnej oceny oraz kontaktu z Kliniką", "formularz nie jest zawarciem umowy o leczenie ani rezerwacją terminu", "podawane dane muszą być prawdziwe i dotyczyć osoby wysyłającej zapytanie lub osoby, która upoważniła ją do kontaktu", "nie opisuj w formularzu stanu zdrowia ani leków, jeżeli nie jest to konieczne; jeśli to zrobisz, wyrażasz zgodę opisaną w polityce prywatności", "nie przesyłaj zdjęć ani dokumentacji medycznej przez formularz; o sposobie ich przekazania poinformujemy w odpowiedzi", "Operator może odmówić odpowiedzi na zapytania nadużywające formularza, zawierające treści bezprawne lub wysyłane automatycznie", "przed rozpoczęciem leczenia pacjent przekazuje Klinice pełne i prawdziwe informacje o stanie zdrowia, przyjmowanych lekach i alergiach; nieprzekazanie ich może wpłynąć na bezpieczeństwo i zakres leczenia"] },
      { title: "7. Zasady korzystania i prawa autorskie", paragraphs: ["7.1. Zabronione jest dostarczanie treści bezprawnych, podszywanie się pod inną osobę, ingerowanie w działanie Serwisu oraz zautomatyzowane przesyłanie zapytań.", "7.2. Treści Serwisu, grafiki i zdjęcia są chronione prawem autorskim. Dozwolone jest cytowanie fragmentów z podaniem źródła i adresu strony oraz indeksowanie przez wyszukiwarki i asystentów AI zgodnie z plikiem robots.txt. Kopiowanie całości lub istotnych części w celach komercyjnych wymaga zgody Operatora."] },
      { title: "8. Odpowiedzialność", paragraphs: ["8.1. Żadne postanowienie Regulaminu nie wyłącza ani nie ogranicza odpowiedzialności za szkodę na osobie, za szkodę wyrządzoną umyślnie ani praw konsumenta wynikających z bezwzględnie obowiązujących przepisów.", "8.2. Operator dokłada należytej staranności, aby treści były rzetelne i aktualne, ale mogą się zmieniać; wskazujemy datę aktualizacji i źródła.", "8.3. Bez uszczerbku dla pkt 8.1, w granicach dopuszczalnych prawem Operator nie odpowiada za przerwy lub błędy techniczne niezależne od Operatora, za treści i działanie stron zewnętrznych, do których prowadzą linki, ani za szkody wynikłe z samodzielnego zastosowania informacji z Serwisu bez konsultacji lekarskiej.", "8.4. Wobec użytkownika niebędącego konsumentem odpowiedzialność Operatora ogranicza się do rzeczywistej szkody i do wysokości, której Operator mógł się spodziewać, z wyłączeniem utraconych korzyści, w zakresie dozwolonym prawem.", "8.5. Odpowiedzialność za leczenie określają odrębna umowa z Kliniką i przepisy prawa właściwego dla tej umowy."] },
      { title: "9. Dane osobowe", paragraphs: ["Zasady przetwarzania danych osobowych opisuje polityka prywatności, a zasady dotyczące plików cookies i pamięci przeglądarki: polityka cookies. Przez formularz nie zbieramy numeru paszportu ani danych o locie."] },
      { title: "10. Reklamacje", paragraphs: [`10.1. Reklamację dotyczącą działania Serwisu można złożyć e-mailem na adres ${EMAIL}. Powinna zawierać imię i nazwisko, dane kontaktowe, wskazanie strony lub usługi oraz opis zastrzeżenia i oczekiwany sposób rozwiązania.`, "10.2. Operator potwierdza otrzymanie reklamacji i ustosunkowuje się do niej w terminie 14 dni od jej otrzymania. Jeżeli potrzebne są dodatkowe informacje lub badanie sprawy, w tym terminie informuje o stanie sprawy i przewidywanym terminie rozstrzygnięcia. Odpowiedź jest przesyłana na adres e-mail podany w zgłoszeniu.", "10.3. Reklamacje dotyczące leczenia i organizacji wyjazdu rozpatrywane są zgodnie z umową z Kliniką oraz zasadami opisanymi na stronie „Reklamacje i zgłoszenia”."] },
      { title: "11. Prawo właściwe i spory", paragraphs: ["11.1. Regulamin i usługi elektroniczne świadczone przez Serwis podlegają prawu Republiki Turcji. Wobec konsumenta wybór ten nie pozbawia go ochrony przyznanej bezwzględnie obowiązującymi przepisami państwa jego zwykłego pobytu, o ile mają one zastosowanie.", "11.2. Konsument może dochodzić roszczeń przed sądem właściwym według bezwzględnie obowiązujących przepisów. W sporach z użytkownikami niebędącymi konsumentami właściwy jest sąd w Antalyi.", "11.3. Konsument może skorzystać z bezpłatnej pomocy rzecznika konsumentów oraz z informacji UOKiK; konsument mieszkający w Wielkiej Brytanii może skorzystać z informacji Citizens Advice. Operator ocenia w danej sprawie możliwość pozasądowego rozwiązania sporu, o czym informuje w odpowiedzi na reklamację."] },
      { title: "12. Zmiany Regulaminu i postanowienia końcowe", paragraphs: ["12.1. Operator może zmienić Regulamin z ważnych przyczyn: zmiany przepisów, zmiany zakresu lub sposobu działania Serwisu albo względów bezpieczeństwa. Zmiany nie dotyczą usług już wykonanych. Zmieniony Regulamin jest udostępniany na tej stronie; użytkownik może zakończyć korzystanie z usługi w każdej chwili, a dalsze korzystanie po publikacji oznacza przyjęcie zmian.", "12.2. Poprzednie wersje Regulaminu udostępniamy na żądanie. Regulamin jest sporządzony w języku polskim.", VERSION] }
    ],
    sources: [{ label: "Polityka prywatności", href: "/polityka-prywatnosci" }, { label: "Polityka cookies", href: "/cookies" }, { label: "Właściciel serwisu", href: "/wlasciciel-serwisu" }, { label: "Reklamacje i zgłoszenia", href: "/reklamacje" }, { label: "Korekty i zgłaszanie błędów", href: "/korekty" }, { label: "UOKiK: informacje i pomoc dla konsumentów", href: "https://uokik.gov.pl" }]
  },
  "polityka-prywatnosci": {
    slug: "polityka-prywatnosci", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Polityka prywatności",
    description: "Jak serwis Zęby w Turcji przetwarza dane: administrator, zakres, podstawy, odbiorcy, przekazywanie do Turcji i USA, okres przechowywania oraz Twoje prawa.",
    eyebrow: "Dokument prawny", h1: "Polityka prywatności",
    lead: "Ten dokument opisuje, jakie dane zbieramy przez serwis leczeniezebowwturcji.pl, w jakim celu, komu je przekazujemy i jakie prawa Ci przysługują.",
    answer: `Administratorem danych jest ${NAME}. Dane z formularza służą do odpowiedzi na zapytanie o wstępną ocenę. Nie opisuj stanu zdrowia ani nie przesyłaj dokumentacji medycznej przez formularz. Nie sprzedajemy danych i nie wysyłamy reklam bez odrębnej zgody.`,
    sections: [
      { title: "1. Administrator i kontakt", paragraphs: [`Administratorem danych osobowych jest ${NAME}, ${ADDRESS}. Administrator ma siedzibę w Turcji. Ponieważ kierujemy ofertę do osób przebywających w Unii Europejskiej, przy przetwarzaniu ich danych kierujemy się zasadami RODO oraz tureckiej ustawy o ochronie danych osobowych nr 6698 (KVKK). Wobec osób przebywających w Wielkiej Brytanii kierujemy się zasadami brytyjskiego RODO (UK GDPR) i ustawy Data Protection Act 2018. W sprawach danych osobowych napisz na adres ${EMAIL}.`] },
      { title: "2. Jakie dane przetwarzamy", bullets: ["dane z formularza: imię i nazwisko, telefon, numer WhatsApp, adres e-mail, kraj oraz opcjonalna wiadomość", "dane z dalszej korespondencji (e-mail, telefon, WhatsApp) prowadzonej w sprawie zapytania", "informacje o stronie, z której wysłano zapytanie (adres strony, parametry UTM); zapisujemy je razem z zapytaniem wyłącznie jako informację o źródle wejścia", "dane techniczne przetwarzane przy wyświetlaniu strony, w tym adres IP i dane przeglądarki w logach hostingu, oraz zagregowane statystyki odsłon i wydajności, bez plików cookies (zob. polityka cookies)"] },
      { title: "3. Cele i podstawy prawne", bullets: ["odpowiedź na zapytanie i przygotowanie wstępnej oceny: art. 6 ust. 1 lit. b RODO (działania na Twoje żądanie przed zawarciem umowy)", "obsługa korespondencji, zgłoszeń i reklamacji, zapewnienie bezpieczeństwa i zapobieganie nadużyciom formularza oraz dochodzenie lub obrona roszczeń: art. 6 ust. 1 lit. f RODO (prawnie uzasadniony interes administratora)", "statystyki odsłon i wydajności serwisu: art. 6 ust. 1 lit. f RODO", "po zawarciu umowy o leczenie: realizacja umowy (art. 6 ust. 1 lit. b RODO) oraz prowadzenie dokumentacji medycznej i dochodzenie roszczeń (art. 9 ust. 2 lit. h i f RODO)", "dane o zdrowiu, jeżeli je podasz w wiadomości: art. 9 ust. 2 lit. a RODO, czyli Twoja wyraźna zgoda, tylko w zakresie niezbędnym do odpowiedzi"] },
      { title: "4. Dobrowolność, profilowanie i marketing", paragraphs: ["Podanie danych w formularzu jest dobrowolne, ale potrzebne do odpowiedzi. Nie podejmujemy wobec Ciebie decyzji w sposób zautomatyzowany ani nie profilujemy Cię w rozumieniu RODO. Nie wykorzystamy danych z formularza do wysyłania informacji handlowych niezwiązanych z Twoim zapytaniem bez Twojej odrębnej zgody. Serwis nie jest skierowany do osób poniżej 18 lat; w ich sprawie kontaktuj się przez opiekuna prawnego."] },
      { title: "5. Dane o zdrowiu, zdjęcia i dokumentacja", paragraphs: ["Nie opisuj w formularzu stanu zdrowia ani leków, jeżeli nie jest to konieczne. Jeżeli to zrobisz, wyrażasz wyraźną zgodę (art. 9 ust. 2 lit. a RODO) na przetwarzanie tych danych w celu odpowiedzi na zapytanie. Zgodę możesz cofnąć w każdej chwili, pisząc na adres z sekcji 1; cofnięcie nie wpływa na zgodność z prawem przetwarzania przed cofnięciem, a my usuniemy wiadomość z naszych systemów w rozsądnym terminie, z zastrzeżeniem ochrony prawnej przed roszczeniami.", "Nie przesyłaj zdjęć ani dokumentacji medycznej przez formularz. O sposobie ich przekazania poinformujemy w odpowiedzi. Jeżeli wybierzesz kontakt przez WhatsApp, komunikacja odbywa się na zasadach tej usługi (dostawca w EOG: WhatsApp Ireland Limited) i wiąże się z ryzykiem właściwym dla komunikatorów internetowych."] },
      { title: "6. Dane pacjentów kliniki poza formularzem", paragraphs: ["Po rozpoczęciu leczenia klinika Akdeniz Dental, prowadzona przez tego samego administratora, przetwarza dane potrzebne do leczenia i organizacji pobytu, w tym dane identyfikacyjne i dokument podróży, informacje o locie i zakwaterowaniu oraz dokumentację medyczną. Odbywa się to poza tym serwisem i jego formularzem, w systemie kliniki. Tych danych nie publikujemy w serwisie, w danych strukturalnych ani w analityce.", "Dokumentacja medyczna jest przechowywana przez okres wynikający z przepisów prawa tureckiego. Pytania o dane pacjentów kliniki kieruj na adres z sekcji 1."] },
      { title: "7. Publikacja przypadków, opinii i statystyk", bullets: ["zdjęcia przed i po, opisy przypadków i opinie pacjentów publikujemy tylko za pisemną zgodą pacjenta; zgodę można cofnąć, a materiał usuwamy bez zbędnej zwłoki", "nie publikujemy danych identyfikujących, w tym numeru paszportu, danych lotu, daty urodzenia ani dokumentacji medycznej", "liczby dotyczące pacjentów podajemy wyłącznie w formie zagregowanej, z ukryciem małych liczebności oraz z datą i opisem sposobu liczenia"] },
      { title: "8. Odbiorcy danych", paragraphs: ["Zgłoszenia z formularza przekazuje do administratora usługa Formspree (Formspree, Inc., USA), działająca jako podmiot przetwarzający. Serwis jest hostowany i mierzony za pomocą usług Vercel Inc. (USA). Jeżeli zlecisz organizację pobytu lub badań, dane mogą być przekazane podmiotom niezbędnym do ich wykonania (na przykład hotelowi, przewoźnikowi lub laboratorium) w niezbędnym zakresie. Dane mogą otrzymać także organy, jeśli wymaga tego prawo.", "Nie sprzedajemy danych użytkowników."] },
      { title: "9. Przekazywanie danych poza EOG", paragraphs: ["Administrator ma siedzibę w Turcji, a dostawcy Formspree i Vercel mogą przetwarzać dane w USA. Dla Turcji Komisja Europejska nie wydała decyzji o odpowiednim stopniu ochrony, co oznacza, że dane przekazywane do Turcji nie korzystają z gwarancji RODO. Przekazanie danych z formularza do administratora jest niezbędne do odpowiedzi na Twoje zapytanie (art. 49 ust. 1 lit. b RODO), a w zakresie danych o zdrowiu opiera się na Twojej wyraźnej zgodzie, wyrażonej po poinformowaniu Cię o tym ryzyku (art. 49 ust. 1 lit. a RODO). Zasady przetwarzania danych przez dostawców w USA opisują ich dokumenty wskazane w źródłach poniżej. Informacje o zabezpieczeniach możesz uzyskać, pisząc na adres z sekcji 1."] },
      { title: "10. Okres przechowywania", bullets: ["dane z zapytania: do czasu zakończenia obsługi sprawy, a następnie nie dłużej niż do upływu terminów przedawnienia roszczeń", "dane techniczne w logach hostingu: zgodnie z ustawieniami dostawcy hostingu, przez okres niezbędny do zapewnienia bezpieczeństwa i działania serwisu", "dane z umowy o leczenie i dokumentacja medyczna: przez okres wynikający z przepisów prawa tureckiego i przepisów podatkowych", "dane zebrane na podstawie zgody: do jej cofnięcia, chyba że dalsze przechowywanie jest wymagane lub uzasadnione inną podstawą prawną", "po upływie okresu dane usuwamy lub anonimizujemy"] },
      { title: "11. Twoje prawa", paragraphs: ["Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania i przenoszenia. Masz też prawo w dowolnym momencie wnieść sprzeciw wobec przetwarzania opartego na prawnie uzasadnionym interesie administratora, z przyczyn związanych z Twoją szczególną sytuacją; zwracamy na to uwagę osobno, ponieważ prawo to wymaga wyraźnego wskazania. Jeżeli przetwarzanie opiera się na zgodzie, możesz ją w każdej chwili cofnąć. Wniosek wyślij na adres z sekcji 1; odpowiadamy w ciągu miesiąca.", "Masz prawo złożyć skargę do organu nadzorczego, w szczególności do Prezesa Urzędu Ochrony Danych Osobowych lub organu w państwie Twojego zwykłego pobytu; w Wielkiej Brytanii jest to Information Commissioner’s Office (ICO).", "Zgodnie z art. 10 i 11 ustawy nr 6698 informujemy, że dane zbieramy za pośrednictwem formularza elektronicznego i korespondencji, na podstawach wskazanych wyżej. Wniosek o wykonanie praw z art. 11 tej ustawy możesz złożyć pisemnie na adres z sekcji 1; odpowiemy najpóźniej w ciągu 30 dni. Po zwróceniu się do administratora możesz złożyć skargę do tureckiej Rady Ochrony Danych Osobowych (Kişisel Verileri Koruma Kurulu)."] },
      { title: "12. Bezpieczeństwo i zmiany", paragraphs: ["Stosujemy środki techniczne i organizacyjne adekwatne do ryzyka, w tym szyfrowane połączenie (HTTPS). W razie naruszenia ochrony danych powiadomimy właściwy organ i osoby, których to dotyczy, w przypadkach wymaganych prawem. Istotne zmiany polityki wskażemy na tej stronie.", VERSION] }
    ],
    sources: [{ label: "Polityka cookies", href: "/cookies" }, { label: "O serwisie: dane operatora", href: "/o-nas" }, { label: "Formspree: polityka prywatności", href: "https://formspree.io/legal/privacy-policy/" }, { label: "Vercel: Privacy Notice", href: "https://vercel.com/legal/privacy-notice" }, { label: "UODO: prawa osób, których dane dotyczą", href: "https://uodo.gov.pl/pl/493/155" }, { label: "UODO: skarga do Prezesa UODO", href: "https://uodo.gov.pl/pl/138/155" }, { label: "ICO: jak złożyć skargę (Make a complaint)", href: "https://ico.org.uk/make-a-complaint/" }]
  },
  cookies: {
    slug: "cookies", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Polityka cookies",
    description: "Cookies i analityka w serwisie Zęby w Turcji: brak własnych cookies i danych w pamięci urządzenia, analityka Vercel bez cookies oraz ustawienia przeglądarki.",
    eyebrow: "Dokument prawny", h1: "Polityka cookies", lead: "Serwis nie ustawia własnych plików cookies, nie zapisuje własnych danych w pamięci urządzenia i nie wdraża marketingowych ani reklamowych narzędzi śledzących.",
    answer: "Serwis nie ustawia własnych plików cookies i nie zapisuje własnych danych w localStorage ani sessionStorage. Statystyki odsłon i wydajności zbiera Vercel Web Analytics oraz Speed Insights, które według dostawcy działają bez plików cookies. Formularz nie wymaga zgody na cookies.",
    sections: [
      { title: "Co jest używane", bullets: ["własne pliki cookies oraz własne dane w localStorage i sessionStorage: nie używamy", "analityka: Vercel Web Analytics i Speed Insights, zagregowane dane o odsłonach i wydajności (na przykład adres strony, źródło wejścia, typ przeglądarki i urządzenia, kraj), bez plików cookies według dostawcy; podstawa: prawnie uzasadniony interes administratora", "zdarzenie statystyczne o wejściu z asystenta AI jest zapamiętywane tylko w pamięci otwartej strony i nie jest zapisywane na urządzeniu", "narzędzia reklamowe i marketingowe: nie używamy"] },
      { title: "Linki do stron zewnętrznych", paragraphs: ["Po kliknięciu linków do usług zewnętrznych, takich jak Trustpilot, Mapy Google, WhatsApp czy strona kliniki, obowiązują zasady plików cookies i prywatności tych usług, na które Operator nie ma wpływu."] },
      { title: "Ustawienia przeglądarki", paragraphs: ["Możesz w każdej chwili usunąć dane przechowywane przez przeglądarkę lub zablokować cookies w jej ustawieniach. Serwis działa także po ich zablokowaniu."] },
      { title: "Zmiany", paragraphs: ["Jeżeli w przyszłości zostanie uruchomione narzędzie wymagające zgody, najpierw zaktualizujemy tę stronę i uruchomimy mechanizm zgody. Dane administratora i zasady przetwarzania opisuje polityka prywatności.", VERSION] }
    ],
    sources: [{ label: "Polityka prywatności", href: "/polityka-prywatnosci" }, { label: "Vercel: Privacy Notice", href: "https://vercel.com/legal/privacy-notice" }]
  },
  reklamacje: {
    slug: "reklamacje", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Reklamacje i zgłoszenia",
    description: "Jak zgłosić reklamację lub skargę dotyczącą serwisu i leczenia: kontakt, wymagane dane, termin odpowiedzi, ocena przez klinikę oraz instytucje pomocy.",
    eyebrow: "Wsparcie", h1: "Reklamacje i zgłoszenia", lead: "Rozróżniamy zgłoszenia dotyczące działania serwisu, organizacji wyjazdu oraz leczenia wykonanego w klinice.",
    answer: `Reklamację lub skargę wyślij na adres ${EMAIL}, opisując sprawę i dołączając dane do kontaktu. Operator ustosunkowuje się do niej w terminie 14 dni. W sprawach leczenia najpierw zgłoś problem klinice, aby mogła go ocenić.`,
    sections: [
      { title: "Jak zgłosić reklamację", bullets: [`napisz na adres ${EMAIL}; zgłoszenie nie wymaga szczególnej formy`, "podaj imię i nazwisko, dane do kontaktu oraz opis sprawy i oczekiwany sposób rozwiązania (na przykład poprawa, zwrot, wyjaśnienie)", "wskaż adres strony albo datę i rodzaj usługi, której dotyczy zgłoszenie", "dołącz dokumenty dotyczące sprawy (nie dołączaj dokumentacji medycznej bez potwierdzenia sposobu bezpiecznego przekazania)", "Operator potwierdza przyjęcie zgłoszenia i ustosunkowuje się do niego w terminie 14 dni od otrzymania; jeżeli sprawa wymaga badania lub dokumentacji, w tym terminie informuje o stanie sprawy i przewidywanym terminie rozstrzygnięcia"] },
      { title: "Czego dotyczy zgłoszenie", bullets: ["działanie serwisu i treści: błędy opisuje także strona „Korekty”", "koordynacja transferów i zakwaterowania, jeżeli była objęta umową: zgłoś Operatorowi jak najszybciej po stwierdzeniu problemu", "leczenie wykonane w klinice: zgłoś Klinice prowadzonej przez Operatora; warunki ewentualnej gwarancji, kontroli i usunięcia wad określa umowa o leczenie, dlatego poproś o nie na piśmie przed podpisaniem"] },
      { title: "Zgłoszenia dotyczące leczenia", paragraphs: ["Zgłoś problem możliwie szybko po jego zauważeniu i opisz go, najlepiej ze zdjęciami oraz dokumentacją z kolejnych wizyt. Zanim zlecisz korektę lub leczenie powikłań innemu lekarzowi, umożliw Klinice ocenę i, jeżeli stwierdzi wadę objętą umową lub gwarancją, nieodpłatną korektę na miejscu lub w uzgodniony sposób. Klinika może poprosić o wizytę kontrolną, zdalną konsultację lub opinię lekarza prowadzącego w Polsce.", "W stanach nagłych skorzystaj z pomocy najbliższego lekarza i niezwłocznie przekaż nam dokumentację. Zwrot kosztów leczenia podjętego u innego lekarza bez uprzedniej możliwości oceny przez Klinikę rozpatrujemy indywidualnie, w granicach wynikających z umowy i bezwzględnie obowiązujących przepisów. Przy ocenie uwzględniamy zalecenia lekarza i informacje o stanie zdrowia przekazane Klinice. Prawa pacjenta i konsumenta wynikające z bezwzględnie obowiązujących przepisów pozostają bez zmian."] },
      { title: "Zanim podpiszesz umowę o leczenie", bullets: ["pisemny plan leczenia z kosztami i etapami", "jasne warunki zaliczki lub zadatku, odwołania i zwrotu", "wskazanie podmiotu odpowiedzialnego za leczenie oraz zakres ewentualnej koordynacji wyjazdu", "zasady opieki po leczeniu i kontaktu po powrocie do Polski", "pisemne warunki gwarancji, jeżeli jest oferowana, i wymagane kontrole", "informację o użytych materiałach i dostęp do dokumentacji leczenia"] },
      { title: "Instytucje, do których możesz się zwrócić", paragraphs: ["Informacje o prawach pacjenta przy leczeniu za granicą publikuje portal pacjent.gov.pl. W sprawach konsumenckich pomoc oferują rzecznicy konsumentów i UOKiK, a w sprawach zaliczki i zadatku porady publikuje UOKiK. Europejskie Centrum Konsumenckie udziela informacji o prawach konsumenta, ale jego pomoc w sporach obejmuje m.in. przedsiębiorców z państw UE, Norwegii i Islandii. W sprawach dotyczących leczenia w Turcji można zwrócić się także do tureckiego Ministerstwa Zdrowia (centrum kontaktowe SABİM; numer 184 działa z tureckich numerów telefonu) oraz do wojewódzkiej dyrekcji zdrowia w Antalyi (Antalya İl Sağlık Müdürlüğü). Osoby mieszkające w Wielkiej Brytanii mogą uzyskać ogólne informacje o prawach konsumenta w Citizens Advice, a w sprawach dotyczących pożyczkodawcy autoryzowanego w UK pomoc oferuje Financial Ombudsman Service."] }
    ],
    sources: [{ label: "Korekty i zgłaszanie błędów", href: "/korekty" }, { label: "pacjent.gov.pl: leczenie za granicą", href: "https://pacjent.gov.pl/leczenie-za-granica" }, { label: "Europejskie Centrum Konsumenckie: zgłoś skargę i informacje o prawach", href: "https://konsument.gov.pl/zglos-skarge/" }, { label: "UOKiK: Zadatek czy zaliczka?", href: "https://archiwum.uokik.gov.pl/aktualnosci.php?news_id=11145" }, { label: "Citizens Advice: prawa konsumenta w UK", href: "https://www.citizensadvice.org.uk" }, { label: "Financial Ombudsman Service", href: "https://www.financial-ombudsman.org.uk" }]
  }
};
