import type { PageContent } from "./site";
import { OPERATOR } from "./operator";

const NAME = OPERATOR.legalName ?? "operator serwisu";
const ADDRESS = OPERATOR.streetAddress ? `${OPERATOR.streetAddress}, ${[OPERATOR.postalCode, OPERATOR.locality].filter(Boolean).join(" ")}, ${OPERATOR.region ?? ""}, ${OPERATOR.country ?? ""}` : "adres podany na stronie „O serwisie”";
const EMAIL = OPERATOR.email ?? "adres e-mail podany na stronie kontaktowej";
const VERSION = "Obecna wersja obowiązuje od 2 października 2026 r.";

/** Legal pages. Drafted to protect the operator within mandatory consumer and data-protection law; a lawyer must confirm them (see docs/consent-and-data-handling.md). */
export const legalPages: Record<string, PageContent> = {
  regulamin: {
    slug: "regulamin", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Regulamin serwisu",
    description: "Regulamin serwisu Zęby w Turcji: charakter informacyjny, zasady korzystania z formularza, ceny orientacyjne, odpowiedzialność, reklamacje i prawo właściwe.",
    eyebrow: "Dokument prawny", h1: "Regulamin serwisu", lead: "Serwis ma charakter informacyjny i komercyjny. Treści nie są diagnozą, ofertą leczenia ani umową o świadczenie usług medycznych.",
    answer: `Serwis prowadzi ${NAME}. Treści mają charakter informacyjny i komercyjny, nie są diagnozą ani wiążącą ofertą, a o leczeniu decyduje lekarz po badaniu. Zapytanie z formularza nie jest umową o leczenie.`,
    sections: [
      { title: "1. Postanowienia ogólne", paragraphs: [`1.1. Serwis leczeniezebowwturcji.pl („Serwis”) prowadzi ${NAME}, ${ADDRESS} („Operator”). Operator prowadzi także klinikę Akdeniz Dental w Antalyi („Klinika”). Kontakt: ${EMAIL}.`, "1.2. Regulamin określa zasady korzystania z Serwisu i jest udostępniony nieodpłatnie na stronie, w formie umożliwiającej jego pobranie, utrwalenie i wydrukowanie.", "1.3. Korzystanie z Serwisu oznacza akceptację Regulaminu w zakresie usług elektronicznych opisanych poniżej. Jeżeli nie akceptujesz Regulaminu, zaprzestań korzystania z Serwisu."] },
      { title: "2. Usługi elektroniczne i wymagania techniczne", paragraphs: ["2.1. Operator świadczy nieodpłatnie dwie usługi elektroniczne: udostępnianie treści informacyjnych oraz przyjmowanie zapytań przez formularz kontaktowy. Umowy o ich świadczenie zawierane są z chwilą rozpoczęcia korzystania i mogą zostać zakończone w każdej chwili przez zaprzestanie korzystania.", "2.2. Do korzystania z Serwisu potrzebne są urządzenie z dostępem do internetu, aktualna przeglądarka z włączoną obsługą JavaScript oraz, dla formularza, adres e-mail lub numer telefonu."] },
      { title: "3. Charakter treści i brak relacji lekarz–pacjent", bullets: ["treści mają charakter ogólny, informacyjny i edukacyjny oraz reklamowy wobec usług Kliniki; Serwis oznacza treści komercyjne jako informację komercyjną", "korzystanie z Serwisu, w tym wysłanie zapytania i otrzymanie wstępnej oceny, nie tworzy relacji lekarz–pacjent ani nie jest udzieleniem świadczenia zdrowotnego", "materiały nie służą do samodzielnej diagnozy ani do podejmowania decyzji o leczeniu bez badania; decyzję medyczną podejmuje lekarz po badaniu i uzyskaniu pełnych informacji o stanie zdrowia", "w stanach nagłych zagrażających zdrowiu lub życiu skontaktuj się z numerem alarmowym 112 lub lokalną służbą ratunkową; Serwis nie jest do tego przeznaczony", "wyniki leczenia są indywidualne; zdjęcia, opisy i opinie mają charakter ilustracyjny i nie gwarantują takiego samego rezultatu u innej osoby"] },
      { title: "4. Ceny i oferta", paragraphs: ["4.1. Ceny, kursy walut i zakres świadczeń w Serwisie są orientacyjne, mają datę aktualizacji i nie stanowią oferty w rozumieniu Kodeksu cywilnego, lecz zaproszenie do zawarcia umowy.", "4.2. Wiążący plan leczenia, cena, harmonogram i warunki płatności wynikają wyłącznie z pisemnej oferty lub umowy Kliniki zawartej po badaniu. Wstępna ocena na podstawie zapytania jest orientacyjna i może się zmienić po badaniu klinicznym i diagnostyce."] },
      { title: "5. Formularz kontaktowy", bullets: ["wysłanie formularza jest dobrowolne i służy uzyskaniu bezpłatnej wstępnej oceny oraz kontaktu z Kliniką", "formularz nie jest zawarciem umowy o leczenie ani rezerwacją terminu", "podawane dane muszą być prawdziwe i dotyczyć osoby wysyłającej zapytanie lub osoby, która upoważniła ją do kontaktu", "nie przesyłaj zdjęć ani dokumentacji medycznej przez formularz, dopóki nie otrzymasz potwierdzenia bezpiecznego kanału", "Operator może odmówić odpowiedzi na zapytania nadużywające formularza, zawierające treści bezprawne lub wysyłane automatycznie", "przed rozpoczęciem leczenia pacjent przekazuje Klinice pełne i prawdziwe informacje o stanie zdrowia, przyjmowanych lekach i alergiach; nieprzekazanie ich może wpłynąć na bezpieczeństwo i zakres leczenia"] },
      { title: "6. Zasady korzystania i prawa autorskie", paragraphs: ["6.1. Zabronione jest dostarczanie treści bezprawnych, podszywanie się pod inną osobę, ingerowanie w działanie Serwisu oraz zautomatyzowane przesyłanie zapytań.", "6.2. Treści Serwisu, grafiki i zdjęcia są chronione prawem autorskim. Dozwolone jest cytowanie fragmentów z podaniem źródła i adresu strony oraz indeksowanie przez wyszukiwarki i asystentów AI zgodnie z plikiem robots.txt. Kopiowanie całości lub istotnych części w celach komercyjnych wymaga zgody Operatora."] },
      { title: "7. Odpowiedzialność", paragraphs: ["7.1. Operator dokłada należytej staranności, aby treści były rzetelne i aktualne, ale mogą się zmieniać; wskazujemy datę aktualizacji i źródła.", "7.2. W granicach dopuszczalnych prawem Operator nie odpowiada za przerwy lub błędy techniczne niezależne od Operatora, za treści i działanie stron zewnętrznych, do których prowadzą linki, ani za szkody wynikłe z samodzielnego zastosowania informacji z Serwisu bez konsultacji lekarskiej.", "7.3. Wobec użytkownika niebędącego konsumentem odpowiedzialność Operatora ogranicza się do rzeczywistej szkody i do wysokości, której Operator mógł się spodziewać, z wyłączeniem utraconych korzyści, w zakresie dozwolonym prawem.", "7.4. Żadne postanowienie Regulaminu nie wyłącza ani nie ogranicza odpowiedzialności za szkodę na osobie, za szkodę wyrządzoną umyślnie ani praw konsumenta wynikających z bezwzględnie obowiązujących przepisów. Odpowiedzialność za leczenie określają odrębna umowa z Kliniką i przepisy prawa właściwego dla tej umowy."] },
      { title: "8. Dane osobowe", paragraphs: ["Zasady przetwarzania danych osobowych opisuje polityka prywatności, a zasady plików cookies polityka cookies. Przez formularz nie zbieramy numeru paszportu ani danych o locie."] },
      { title: "9. Reklamacje i spory", paragraphs: ["9.1. Reklamacje dotyczące działania Serwisu można składać na adres e-mail Operatora. Operator odpowiada w terminie 14 dni od otrzymania zgłoszenia. Szczegóły opisuje strona „Reklamacje i zgłoszenia”.", "9.2. Konsument może skorzystać z pozasądowych sposobów rozpatrywania reklamacji i dochodzenia roszczeń, w szczególności z pomocy Europejskiego Centrum Konsumenckiego w Polsce.", "9.3. Do Regulaminu i usług elektronicznych świadczonych przez Serwis stosuje się prawo wskazane w przepisach właściwych dla umowy; wobec konsumenta wybór prawa nie pozbawia go ochrony przyznanej bezwzględnie obowiązującymi przepisami państwa jego zwykłego pobytu. Konsument może dochodzić roszczeń przed sądem właściwym według bezwzględnie obowiązujących przepisów. W sporach z przedsiębiorcami właściwy jest sąd w Antalyi, a stosuje się prawo Republiki Turcji."] },
      { title: "10. Zmiany Regulaminu i postanowienia końcowe", paragraphs: ["10.1. Operator może zmienić Regulamin z ważnych przyczyn: zmiany przepisów, zmiany zakresu lub sposobu działania Serwisu albo względów bezpieczeństwa. Zmiany publikujemy na tej stronie i obowiązują od dnia publikacji, a dla trwających usług od następnego korzystania z Serwisu.", "10.2. Poprzednie wersje Regulaminu udostępniamy na żądanie. Regulamin jest sporządzony w języku polskim.", VERSION] }
    ],
    sources: [{ label: "Polityka prywatności", href: "/polityka-prywatnosci" }, { label: "Polityka cookies", href: "/cookies" }, { label: "Właściciel serwisu", href: "/wlasciciel-serwisu" }, { label: "Reklamacje i zgłoszenia", href: "/reklamacje" }, { label: "Korekty i zgłaszanie błędów", href: "/korekty" }, { label: "Europejskie Centrum Konsumenckie", href: "https://konsument.gov.pl/zglos-skarge/" }]
  },
  "polityka-prywatnosci": {
    slug: "polityka-prywatnosci", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Polityka prywatności",
    description: "Jak serwis Zęby w Turcji przetwarza dane: administrator, zakres, podstawy, odbiorcy, przekazywanie do Turcji i USA, okres przechowywania oraz Twoje prawa.",
    eyebrow: "Dokument prawny", h1: "Polityka prywatności",
    lead: "Ten dokument opisuje, jakie dane zbieramy przez serwis leczeniezebowwturcji.pl, w jakim celu, komu je przekazujemy i jakie prawa Ci przysługują.",
    answer: `Administratorem danych jest ${NAME}. Dane z formularza służą do odpowiedzi na zapytanie o wstępną ocenę. Nie przesyłaj dokumentacji medycznej ani zdjęć przez formularz. Nie sprzedajemy danych i nie wysyłamy reklam bez odrębnej zgody.`,
    sections: [
      { title: "1. Administrator i kontakt", paragraphs: [`Administratorem danych osobowych jest ${NAME}, ${ADDRESS}. Administrator ma siedzibę w Turcji i przetwarza dane zgodnie z RODO w zakresie, w jakim ma ono zastosowanie, oraz z tureckim prawem o ochronie danych osobowych (ustawa nr 6698). W sprawach danych osobowych napisz na adres ${EMAIL}.`] },
      { title: "2. Jakie dane przetwarzamy", bullets: ["dane z formularza: imię i nazwisko, telefon, numer WhatsApp, adres e-mail, kraj oraz opcjonalna wiadomość", "dane z dalszej korespondencji (e-mail, telefon, WhatsApp) prowadzonej w sprawie zapytania", "informacje o stronie i kampanii, z której wysłano zapytanie (adres strony, parametry UTM)", "dane techniczne i zagregowane statystyki odsłon oraz wydajności, bez plików cookies (zob. polityka cookies)", "nie prosimy o dane o zdrowiu w formularzu; nie przesyłaj zdjęć ani dokumentacji medycznej, dopóki nie otrzymasz potwierdzenia bezpiecznego kanału"] },
      { title: "3. Cele i podstawy prawne", bullets: ["odpowiedź na zapytanie i przygotowanie wstępnej oceny: art. 6 ust. 1 lit. b RODO (działania na Twoje żądanie przed zawarciem umowy)", "obsługa korespondencji, zgłoszeń i reklamacji, zapobieganie nadużyciom formularza oraz dochodzenie lub obrona roszczeń: art. 6 ust. 1 lit. f RODO (prawnie uzasadniony interes administratora)", "statystyki odsłon i wydajności serwisu: art. 6 ust. 1 lit. f RODO", "wypełnienie obowiązków prawnych, na przykład podatkowych lub dotyczących dokumentacji, jeżeli zawrzesz umowę o leczenie: art. 6 ust. 1 lit. c RODO", "dane o zdrowiu, jeżeli sam je podasz w wiadomości: art. 9 ust. 2 lit. a RODO, na podstawie Twojej wyraźnej zgody wyrażonej przez ich przesłanie, i tylko w zakresie niezbędnym do odpowiedzi"] },
      { title: "4. Dobrowolność, brak profilowania i marketingu", paragraphs: ["Podanie danych w formularzu jest dobrowolne, ale potrzebne do odpowiedzi. Nie podejmujemy wobec Ciebie decyzji w sposób zautomatyzowany ani nie profilujemy Cię w rozumieniu RODO. Nie wykorzystamy danych z formularza do wysyłania informacji handlowych niezwiązanych z Twoim zapytaniem bez Twojej odrębnej zgody. Serwis nie jest skierowany do osób poniżej 18 lat; w ich sprawie kontaktuj się przez opiekuna prawnego."] },
      { title: "5. Dane pacjentów kliniki poza formularzem", paragraphs: ["Po rozpoczęciu leczenia klinika Akdeniz Dental, prowadzona przez tego samego administratora, przetwarza dane potrzebne do leczenia i organizacji pobytu, w tym dane identyfikacyjne i dokument podróży, informacje o locie i zakwaterowaniu oraz dokumentację medyczną. Odbywa się to poza tym serwisem i jego formularzem, w systemie kliniki. Tych danych nie publikujemy w serwisie, w danych strukturalnych ani w analityce.", "Dokumentacja medyczna jest przechowywana przez okres wynikający z przepisów prawa tureckiego. Pytania o dane pacjentów kliniki kieruj na adres z sekcji 1."] },
      { title: "6. Publikacja przypadków, opinii i statystyk", bullets: ["zdjęcia przed i po, opisy przypadków i opinie pacjentów publikujemy tylko za pisemną zgodą pacjenta; zgodę można cofnąć, a materiał usuwamy bez zbędnej zwłoki", "nie publikujemy danych identyfikujących, w tym numeru paszportu, danych lotu, daty urodzenia ani dokumentacji medycznej", "liczby dotyczące pacjentów podajemy wyłącznie w formie zagregowanej, z ukryciem małych liczebności oraz z datą i opisem sposobu liczenia", "dane z systemu kliniki służą nam do wewnętrznego potwierdzenia, że przypadek lub opinia dotyczy rzeczywistego pacjenta; nie trafiają do serwisu"] },
      { title: "7. Odbiorcy danych", paragraphs: ["Zgłoszenia z formularza przekazuje do administratora usługa Formspree (Formspree, Inc., USA). Serwis jest hostowany i mierzony za pomocą usług Vercel Inc. (USA). Jeżeli wybierzesz kontakt przez WhatsApp, komunikacja podlega zasadom tej usługi. Jeżeli zlecisz organizację pobytu lub badań, dane mogą być przekazane podmiotom niezbędnym do ich wykonania (na przykład hotelowi, przewoźnikowi lub laboratorium) w niezbędnym zakresie. Dostęp mają też podmioty świadczące administratorowi usługi IT i księgowe oraz organy, jeśli wymaga tego prawo.", "Nie sprzedajemy danych użytkowników."] },
      { title: "8. Przekazywanie danych poza EOG", paragraphs: ["Administrator ma siedzibę w Turcji, a dostawcy Formspree i Vercel mogą przetwarzać dane w USA. Dla Turcji Komisja Europejska nie wydała decyzji o odpowiednim stopniu ochrony. Przekazanie danych z formularza jest niezbędne do odpowiedzi na Twoje zapytanie, a w zakresie danych o zdrowiu opiera się na Twojej wyraźnej zgodzie. Informacje o stosowanych zabezpieczeniach możesz uzyskać, pisząc na adres z sekcji 1."] },
      { title: "9. Okres przechowywania", bullets: ["dane z zapytania: do czasu zakończenia obsługi sprawy, a następnie nie dłużej niż do upływu terminów przedawnienia roszczeń", "dane z umowy o leczenie i dokumentacja medyczna: przez okres wynikający z przepisów prawa tureckiego i przepisów podatkowych", "dane zebrane na podstawie zgody: do czasu jej cofnięcia, chyba że dalsze przechowywanie wymaga inna podstawa", "po upływie okresu dane usuwamy lub anonimizujemy"] },
      { title: "10. Twoje prawa", paragraphs: ["Masz prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia oraz sprzeciwu wobec przetwarzania opartego na prawnie uzasadnionym interesie. Jeżeli przetwarzanie opiera się na zgodzie, możesz ją w każdej chwili cofnąć, co nie wpływa na zgodność z prawem przetwarzania przed cofnięciem. Wniosek wyślij na adres z sekcji 1; odpowiadamy w ciągu miesiąca.", "Masz prawo złożyć skargę do organu nadzorczego, w szczególności do Prezesa Urzędu Ochrony Danych Osobowych lub organu w państwie Twojego zwykłego pobytu, a także do tureckiego Kurumu Ochrony Danych Osobowych (KVKK)."] },
      { title: "11. Bezpieczeństwo i zmiany", paragraphs: ["Stosujemy środki techniczne i organizacyjne adekwatne do ryzyka, w tym szyfrowane połączenie (HTTPS) i ograniczenie dostępu do zgłoszeń. W razie naruszenia ochrony danych powiadomimy właściwy organ i osoby, których to dotyczy, w przypadkach wymaganych prawem. Istotne zmiany polityki wskażemy na tej stronie.", VERSION] }
    ],
    sources: [{ label: "Polityka cookies", href: "/cookies" }, { label: "O serwisie: dane operatora", href: "/o-nas" }, { label: "Formspree: polityka prywatności", href: "https://formspree.io/legal/privacy-policy/" }, { label: "Vercel: Privacy Notice", href: "https://vercel.com/legal/privacy-notice" }, { label: "UODO: prawa osób, których dane dotyczą", href: "https://uodo.gov.pl/pl/493/155" }, { label: "UODO: skarga do Prezesa UODO", href: "https://uodo.gov.pl/pl/138/155" }]
  },
  cookies: {
    slug: "cookies", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Polityka cookies",
    description: "Informacje o plikach cookies i analityce w serwisie Zęby w Turcji: brak własnych cookies, analityka Vercel bez cookies, zewnętrzne linki i ustawienia przeglądarki.",
    eyebrow: "Dokument prawny", h1: "Polityka cookies", lead: "Serwis nie ustawia własnych plików cookies i nie wdraża marketingowych ani reklamowych narzędzi śledzących.",
    answer: "Serwis nie ustawia własnych plików cookies. Statystyki odsłon i wydajności zbiera Vercel Web Analytics oraz Speed Insights, które według dostawcy działają bez plików cookies. Formularz kontaktowy nie wymaga zgody na cookies.",
    sections: [
      { title: "Co jest używane", bullets: ["własne pliki cookies: nie ustawiamy", "analityka: Vercel Web Analytics i Speed Insights, zagregowane dane o odsłonach i wydajności (na przykład adres strony, źródło wejścia, typ przeglądarki i urządzenia, kraj), bez plików cookies według dostawcy; podstawa: prawnie uzasadniony interes administratora", "pamięć sesji przeglądarki (sessionStorage): jednorazowy znacznik w trakcie wizyty, który zapobiega wielokrotnemu zapisaniu zdarzenia o pochodzeniu wizyty z asystenta AI", "narzędzia reklamowe i marketingowe: nie używamy"] },
      { title: "Linki do stron zewnętrznych", paragraphs: ["Po kliknięciu linków do usług zewnętrznych, takich jak Trustpilot, Mapy Google, WhatsApp czy strona kliniki, obowiązują zasady plików cookies i prywatności tych usług, na które Operator nie ma wpływu."] },
      { title: "Ustawienia przeglądarki", paragraphs: ["Możesz w każdej chwili usunąć dane przechowywane przez przeglądarkę lub zablokować pamięć sesji w jej ustawieniach. Serwis działa także po zablokowaniu cookies."] },
      { title: "Zmiany", paragraphs: ["Jeżeli w przyszłości zostanie uruchomione narzędzie wymagające zgody, najpierw zaktualizujemy tę stronę i uruchomimy mechanizm zgody. Dane administratora i zasady przetwarzania opisuje polityka prywatności.", VERSION] }
    ],
    sources: [{ label: "Polityka prywatności", href: "/polityka-prywatnosci" }, { label: "Vercel: Privacy Notice", href: "https://vercel.com/legal/privacy-notice" }]
  },
  reklamacje: {
    slug: "reklamacje", published: "2026-10-02", lastUpdated: "2026-10-02", title: "Reklamacje i zgłoszenia",
    description: "Jak zgłosić reklamację lub skargę dotyczącą serwisu i leczenia w klinice: kontakt, wymagane dane, terminy odpowiedzi oraz instytucje, do których można się zwrócić.",
    eyebrow: "Wsparcie", h1: "Reklamacje i zgłoszenia", lead: "Rozróżniamy zgłoszenia dotyczące działania serwisu, organizacji wyjazdu oraz leczenia wykonanego w klinice.",
    answer: `Reklamację lub skargę wyślij na adres ${EMAIL}, opisując sprawę i dołączając dane do kontaktu. Operator odpowiada w terminie 14 dni. Możesz też zwrócić się do instytucji konsumenckich i pacjenckich.`,
    sections: [
      { title: "Jak zgłosić reklamację", bullets: [`napisz na adres ${EMAIL}; zgłoszenie nie wymaga szczególnej formy`, "podaj imię i nazwisko, dane do kontaktu oraz opis sprawy i oczekiwanie (na przykład poprawa, zwrot, wyjaśnienie)", "wskaż adres strony albo datę i rodzaj usługi, której dotyczy zgłoszenie", "dołącz dokumenty dotyczące sprawy (nie dołączaj dokumentacji medycznej bez potwierdzenia bezpiecznego kanału)", "Operator potwierdza przyjęcie zgłoszenia i odpowiada w terminie 14 dni od jego otrzymania; jeżeli sprawa wymaga badania lub dokumentacji, poinformuje o dalszych krokach i przewidywanym terminie"] },
      { title: "Czego dotyczy zgłoszenie", bullets: ["działanie serwisu i treści: błędy opisuje także strona „Korekty”", "organizacja wyjazdu i koordynacja: zgłoś do Operatora jak najszybciej po stwierdzeniu problemu", "leczenie wykonane w klinice: zgłoś do Kliniki prowadzonej przez Operatora; warunki ewentualnej gwarancji, kontroli i usunięcia wad określa umowa o leczenie, dlatego poproś o nie na piśmie przed podpisaniem"] },
      { title: "Zgłoszenia dotyczące leczenia", paragraphs: ["Zgłoś problem możliwie szybko po jego zauważeniu i opisz go, najlepiej ze zdjęciami oraz dokumentacją z kolejnych wizyt. Aby ocenić sprawę, Klinika może poprosić o wizytę kontrolną, zdalną konsultację lub opinię lekarza prowadzącego w Polsce. Przy ocenie uwzględniamy zalecenia lekarza i informacje o stanie zdrowia przekazane Klinice. Prawa pacjenta i konsumenta wynikające z bezwzględnie obowiązujących przepisów pozostają bez zmian."] },
      { title: "Zanim podpiszesz umowę o leczenie", bullets: ["pisemny plan leczenia z kosztami i etapami", "jasne warunki zaliczki lub zadatku, odwołania i zwrotu", "wskazanie podmiotu odpowiedzialnego za leczenie i za organizację wyjazdu", "zasady opieki po leczeniu i kontaktu po powrocie do Polski", "pisemne warunki gwarancji, jeżeli jest oferowana, i wymagane kontrole", "kopię dokumentacji i listę użytych materiałów"] },
      { title: "Instytucje, do których możesz się zwrócić", paragraphs: ["Informacje o prawach pacjenta przy leczeniu za granicą publikuje portal pacjent.gov.pl. W sprawach konsumenckich pomoc oferuje Europejskie Centrum Konsumenckie, a w sprawach zaliczki i zadatku porady publikuje UOKiK."] }
    ],
    sources: [{ label: "Korekty i zgłaszanie błędów", href: "/korekty" }, { label: "pacjent.gov.pl: leczenie za granicą", href: "https://pacjent.gov.pl/leczenie-za-granica" }, { label: "Europejskie Centrum Konsumenckie: zgłoś skargę", href: "https://konsument.gov.pl/zglos-skarge/" }, { label: "UOKiK: Zadatek czy zaliczka?", href: "https://archiwum.uokik.gov.pl/aktualnosci.php?news_id=11145" }]
  }
};
